const listCurrencyIsoData = [
  {
    country: "afghanistan",
    alpha2: "af",
    alpha3: "afg",
    currencyNumeriCode: "004",
  },
  {
    country: "albania",
    alpha2: "al",
    alpha3: "alb",
    currencyNumeriCode: "008",
  },
  {
    country: "algeria",
    alpha2: "dz",
    alpha3: "dza",
    currencyNumeriCode: "012",
  },
  {
    country: "american samoa",
    alpha2: "as",
    alpha3: "asm",
    currencyNumeriCode: "016",
  },
  {
    country: "andorra",
    alpha2: "ad",
    alpha3: "and",
    currencyNumeriCode: "020",
  },
  {
    country: "angola",
    alpha2: "ao",
    alpha3: "ago",
    currencyNumeriCode: "024",
  },
  {
    country: "anguilla",
    alpha2: "ai",
    alpha3: "aia",
    currencyNumeriCode: "660",
  },
  {
    country: "antarctica",
    alpha2: "aq",
    alpha3: "ata",
    currencyNumeriCode: "010",
  },
  {
    country: "antigua and barbuda",
    alpha2: "ag",
    alpha3: "atg",
    currencyNumeriCode: "028",
  },
  {
    country: "argentina",
    alpha2: "ar",
    alpha3: "arg",
    currencyNumeriCode: "032",
  },
  {
    country: "armenia",
    alpha2: "am",
    alpha3: "arm",
    currencyNumeriCode: "051",
  },
  {
    country: "aruba",
    alpha2: "aw",
    alpha3: "abw",
    currencyNumeriCode: "533",
  },
  {
    country: "australia",
    alpha2: "au",
    alpha3: "aus",
    currencyNumeriCode: "036",
  },
  {
    country: "austria",
    alpha2: "at",
    alpha3: "aut",
    currencyNumeriCode: "978",
  },
  {
    country: "azerbaijan",
    alpha2: "az",
    alpha3: "aze",
    currencyNumeriCode: "031",
  },
  {
    country: "bahamas (the)",
    alpha2: "bs",
    alpha3: "bhs",
    currencyNumeriCode: "044",
  },
  {
    country: "bahrain",
    alpha2: "bh",
    alpha3: "bhr",
    currencyNumeriCode: "048",
  },
  {
    country: "bangladesh",
    alpha2: "bd",
    alpha3: "bgd",
    currencyNumeriCode: "050",
  },
  {
    country: "barbados",
    alpha2: "bb",
    alpha3: "brb",
    currencyNumeriCode: "052",
  },
  {
    country: "belarus",
    alpha2: "by",
    alpha3: "blr",
    currencyNumeriCode: "112",
  },
  {
    country: "belgium",
    alpha2: "be",
    alpha3: "bel",
    currencyNumeriCode: "978",
  },
  {
    country: "belize",
    alpha2: "bz",
    alpha3: "blz",
    currencyNumeriCode: "084",
  },
  {
    country: "benin",
    alpha2: "bj",
    alpha3: "ben",
    currencyNumeriCode: "204",
  },
  {
    country: "bermuda",
    alpha2: "bm",
    alpha3: "bmu",
    currencyNumeriCode: "060",
  },
  {
    country: "bhutan",
    alpha2: "bt",
    alpha3: "btn",
    currencyNumeriCode: "064",
  },
  {
    country: "bolivia (plurinational state of)",
    alpha2: "bo",
    alpha3: "bol",
    currencyNumeriCode: "068",
  },
  {
    country: "bonaire, sint eustatius and saba",
    alpha2: "bq",
    alpha3: "bes",
    currencyNumeriCode: "535",
  },
  {
    country: "bosnia and herzegovina",
    alpha2: "ba",
    alpha3: "bih",
    currencyNumeriCode: "070",
  },
  {
    country: "botswana",
    alpha2: "bw",
    alpha3: "bwa",
    currencyNumeriCode: "072",
  },
  {
    country: "bouvet island",
    alpha2: "bv",
    alpha3: "bvt",
    currencyNumeriCode: "074",
  },
  {
    country: "brazil",
    alpha2: "br",
    alpha3: "bra",
    currencyNumeriCode: "076",
  },
  {
    country: "british indian ocean territory (the)",
    alpha2: "io",
    alpha3: "iot",
    currencyNumeriCode: "086",
  },
  {
    country: "brunei darussalam",
    alpha2: "bn",
    alpha3: "brn",
    currencyNumeriCode: "096",
  },
  {
    country: "bulgaria",
    alpha2: "bg",
    alpha3: "bgr",
    currencyNumeriCode: "100",
  },
  {
    country: "burkina faso",
    alpha2: "bf",
    alpha3: "bfa",
    currencyNumeriCode: "854",
  },
  {
    country: "burundi",
    alpha2: "bi",
    alpha3: "bdi",
    currencyNumeriCode: "108",
  },
  {
    country: "cabo verde",
    alpha2: "cv",
    alpha3: "cpv",
    currencyNumeriCode: "132",
  },
  {
    country: "cambodia",
    alpha2: "kh",
    alpha3: "khm",
    currencyNumeriCode: "116",
  },
  {
    country: "cameroon",
    alpha2: "cm",
    alpha3: "cmr",
    currencyNumeriCode: "120",
  },
  {
    country: "canada",
    alpha2: "ca",
    alpha3: "can",
    currencyNumeriCode: "124",
  },
  {
    country: "cayman islands (the)",
    alpha2: "ky",
    alpha3: "cym",
    currencyNumeriCode: "136",
  },
  {
    country: "central african republic (the)",
    alpha2: "cf",
    alpha3: "caf",
    currencyNumeriCode: "140",
  },
  {
    country: "chad",
    alpha2: "td",
    alpha3: "tcd",
    currencyNumeriCode: "148",
  },
  {
    country: "chile",
    alpha2: "cl",
    alpha3: "chl",
    currencyNumeriCode: "152",
  },
  {
    country: "china",
    alpha2: "cn",
    alpha3: "chn",
    currencyNumeriCode: "156",
  },
  {
    country: "christmas island",
    alpha2: "cx",
    alpha3: "cxr",
    currencyNumeriCode: "162",
  },
  {
    country: "cocos (keeling) islands (the)",
    alpha2: "cc",
    alpha3: "cck",
    currencyNumeriCode: "166",
  },
  {
    country: "colombia",
    alpha2: "co",
    alpha3: "col",
    currencyNumeriCode: "170",
  },
  {
    country: "comoros (the)",
    alpha2: "km",
    alpha3: "com",
    currencyNumeriCode: "174",
  },
  {
    country: "congo (the democratic republic of the)",
    alpha2: "cd",
    alpha3: "cod",
    currencyNumeriCode: "180",
  },
  {
    country: "congo (the)",
    alpha2: "cg",
    alpha3: "cog",
    currencyNumeriCode: "178",
  },
  {
    country: "cook islands (the)",
    alpha2: "ck",
    alpha3: "cok",
    currencyNumeriCode: "184",
  },
  {
    country: "costa rica",
    alpha2: "cr",
    alpha3: "cri",
    currencyNumeriCode: "188",
  },
  {
    country: "croatia",
    alpha2: "hr",
    alpha3: "hrv",
    currencyNumeriCode: "978",
  },
  {
    country: "cuba",
    alpha2: "cu",
    alpha3: "cub",
    currencyNumeriCode: "192",
  },
  {
    country: "curaçao",
    alpha2: "cw",
    alpha3: "cuw",
    currencyNumeriCode: "531",
  },
  {
    country: "cyprus",
    alpha2: "cy",
    alpha3: "cyp",
    currencyNumeriCode: "978",
  },
  {
    country: "czechia",
    alpha2: "cz",
    alpha3: "cze",
    currencyNumeriCode: "203",
  },
  {
    country: "côte d'ivoire",
    alpha2: "ci",
    alpha3: "civ",
    currencyNumeriCode: "384",
  },
  {
    country: "denmark",
    alpha2: "dk",
    alpha3: "dnk",
    currencyNumeriCode: "208",
  },
  {
    country: "djibouti",
    alpha2: "dj",
    alpha3: "dji",
    currencyNumeriCode: "262",
  },
  {
    country: "dominica",
    alpha2: "dm",
    alpha3: "dma",
    currencyNumeriCode: "212",
  },
  {
    country: "dominican republic (the)",
    alpha2: "do",
    alpha3: "dom",
    currencyNumeriCode: "214",
  },
  {
    country: "ecuador",
    alpha2: "ec",
    alpha3: "ecu",
    currencyNumeriCode: "218",
  },
  {
    country: "egypt",
    alpha2: "eg",
    alpha3: "egy",
    currencyNumeriCode: "818",
  },
  {
    country: "el salvador",
    alpha2: "sv",
    alpha3: "slv",
    currencyNumeriCode: "222",
  },
  {
    country: "equatorial guinea",
    alpha2: "gq",
    alpha3: "gnq",
    currencyNumeriCode: "226",
  },
  {
    country: "eritrea",
    alpha2: "er",
    alpha3: "eri",
    currencyNumeriCode: "232",
  },
  {
    country: "estonia",
    alpha2: "ee",
    alpha3: "est",
    currencyNumeriCode: "978",
  },
  {
    country: "eswatini",
    alpha2: "sz",
    alpha3: "swz",
    currencyNumeriCode: "748",
  },
  {
    country: "ethiopia",
    alpha2: "et",
    alpha3: "eth",
    currencyNumeriCode: "231",
  },
  {
    country: "falkland islands (the) [malvinas]",
    alpha2: "fk",
    alpha3: "flk",
    currencyNumeriCode: "238",
  },
  {
    country: "faroe islands (the)",
    alpha2: "fo",
    alpha3: "fro",
    currencyNumeriCode: "234",
  },
  {
    country: "fiji",
    alpha2: "fj",
    alpha3: "fji",
    currencyNumeriCode: "242",
  },
  {
    country: "finland",
    alpha2: "fi",
    alpha3: "fin",
    currencyNumeriCode: "978",
  },
  {
    country: "france",
    alpha2: "fr",
    alpha3: "fra",
    currencyNumeriCode: "978",
  },
  {
    country: "french guiana",
    alpha2: "gf",
    alpha3: "guf",
    currencyNumeriCode: "254",
  },
  {
    country: "french polynesia",
    alpha2: "pf",
    alpha3: "pyf",
    currencyNumeriCode: "258",
  },
  {
    country: "french southern territories (the)",
    alpha2: "tf",
    alpha3: "atf",
    currencyNumeriCode: "260",
  },
  {
    country: "gabon",
    alpha2: "ga",
    alpha3: "gab",
    currencyNumeriCode: "266",
  },
  {
    country: "gambia (the)",
    alpha2: "gm",
    alpha3: "gmb",
    currencyNumeriCode: "270",
  },
  {
    country: "georgia",
    alpha2: "ge",
    alpha3: "geo",
    currencyNumeriCode: "268",
  },
  {
    country: "germany",
    alpha2: "de",
    alpha3: "deu",
    currencyNumeriCode: "978",
  },
  {
    country: "ghana",
    alpha2: "gh",
    alpha3: "gha",
    currencyNumeriCode: "288",
  },
  {
    country: "gibraltar",
    alpha2: "gi",
    alpha3: "gib",
    currencyNumeriCode: "292",
  },
  {
    country: "greece",
    alpha2: "gr",
    alpha3: "grc",
    currencyNumeriCode: "978",
  },
  {
    country: "greenland",
    alpha2: "gl",
    alpha3: "grl",
    currencyNumeriCode: "304",
  },
  {
    country: "grenada",
    alpha2: "gd",
    alpha3: "grd",
    currencyNumeriCode: "308",
  },
  {
    country: "guadeloupe",
    alpha2: "gp",
    alpha3: "glp",
    currencyNumeriCode: "312",
  },
  {
    country: "guam",
    alpha2: "gu",
    alpha3: "gum",
    currencyNumeriCode: "316",
  },
  {
    country: "guatemala",
    alpha2: "gt",
    alpha3: "gtm",
    currencyNumeriCode: "320",
  },
  {
    country: "guernsey",
    alpha2: "gg",
    alpha3: "ggy",
    currencyNumeriCode: "831",
  },
  {
    country: "guinea",
    alpha2: "gn",
    alpha3: "gin",
    currencyNumeriCode: "324",
  },
  {
    country: "guinea-bissau",
    alpha2: "gw",
    alpha3: "gnb",
    currencyNumeriCode: "624",
  },
  {
    country: "guyana",
    alpha2: "gy",
    alpha3: "guy",
    currencyNumeriCode: "328",
  },
  {
    country: "haiti",
    alpha2: "ht",
    alpha3: "hti",
    currencyNumeriCode: "332",
  },
  {
    country: "heard island and mcdonald islands",
    alpha2: "hm",
    alpha3: "hmd",
    currencyNumeriCode: "334",
  },
  {
    country: "holy see (the)",
    alpha2: "va",
    alpha3: "vat",
    currencyNumeriCode: "336",
  },
  {
    country: "honduras",
    alpha2: "hn",
    alpha3: "hnd",
    currencyNumeriCode: "340",
  },
  {
    country: "hong kong",
    alpha2: "hk",
    alpha3: "hkg",
    currencyNumeriCode: "344",
  },
  {
    country: "hungary",
    alpha2: "hu",
    alpha3: "hun",
    currencyNumeriCode: "348",
  },
  {
    country: "iceland",
    alpha2: "is",
    alpha3: "isl",
    currencyNumeriCode: "352",
  },
  {
    country: "india",
    alpha2: "in",
    alpha3: "ind",
    currencyNumeriCode: "356",
  },
  {
    country: "indonesia",
    alpha2: "id",
    alpha3: "idn",
    currencyNumeriCode: "360",
  },
  {
    country: "iran (islamic republic of)",
    alpha2: "ir",
    alpha3: "irn",
    currencyNumeriCode: "364",
  },
  {
    country: "iraq",
    alpha2: "iq",
    alpha3: "irq",
    currencyNumeriCode: "368",
  },
  {
    country: "ireland",
    alpha2: "ie",
    alpha3: "irl",
    currencyNumeriCode: "978",
  },
  {
    country: "isle of man",
    alpha2: "im",
    alpha3: "imn",
    currencyNumeriCode: "833",
  },
  {
    country: "israel",
    alpha2: "il",
    alpha3: "isr",
    currencyNumeriCode: "376",
  },
  {
    country: "italy",
    alpha2: "it",
    alpha3: "ita",
    currencyNumeriCode: "978",
  },
  {
    country: "jamaica",
    alpha2: "jm",
    alpha3: "jam",
    currencyNumeriCode: "388",
  },
  {
    country: "japan",
    alpha2: "jp",
    alpha3: "jpn",
    currencyNumeriCode: "392",
  },
  {
    country: "jersey",
    alpha2: "je",
    alpha3: "jey",
    currencyNumeriCode: "832",
  },
  {
    country: "jordan",
    alpha2: "jo",
    alpha3: "jor",
    currencyNumeriCode: "400",
  },
  {
    country: "kazakhstan",
    alpha2: "kz",
    alpha3: "kaz",
    currencyNumeriCode: "398",
  },
  {
    country: "kenya",
    alpha2: "ke",
    alpha3: "ken",
    currencyNumeriCode: "404",
  },
  {
    country: "kiribati",
    alpha2: "ki",
    alpha3: "kir",
    currencyNumeriCode: "296",
  },
  {
    country: "korea (the democratic people's republic of)",
    alpha2: "kp",
    alpha3: "prk",
    currencyNumeriCode: "408",
  },
  {
    country: "korea (the republic of)",
    alpha2: "kr",
    alpha3: "kor",
    currencyNumeriCode: "410",
  },
  {
    country: "kuwait",
    alpha2: "kw",
    alpha3: "kwt",
    currencyNumeriCode: "414",
  },
  {
    country: "kyrgyzstan",
    alpha2: "kg",
    alpha3: "kgz",
    currencyNumeriCode: "417",
  },
  {
    country: "lao people's democratic republic (the)",
    alpha2: "la",
    alpha3: "lao",
    currencyNumeriCode: "418",
  },
  {
    country: "latvia",
    alpha2: "lv",
    alpha3: "lva",
    currencyNumeriCode: "978",
  },
  {
    country: "lebanon",
    alpha2: "lb",
    alpha3: "lbn",
    currencyNumeriCode: "422",
  },
  {
    country: "lesotho",
    alpha2: "ls",
    alpha3: "lso",
    currencyNumeriCode: "426",
  },
  {
    country: "liberia",
    alpha2: "lr",
    alpha3: "lbr",
    currencyNumeriCode: "430",
  },
  {
    country: "libya",
    alpha2: "ly",
    alpha3: "lby",
    currencyNumeriCode: "434",
  },
  {
    country: "liechtenstein",
    alpha2: "li",
    alpha3: "lie",
    currencyNumeriCode: "438",
  },
  {
    country: "lithuania",
    alpha2: "lt",
    alpha3: "ltu",
    currencyNumeriCode: "978",
  },
  {
    country: "luxembourg",
    alpha2: "lu",
    alpha3: "lux",
    currencyNumeriCode: "978",
  },
  {
    country: "macao",
    alpha2: "mo",
    alpha3: "mac",
    currencyNumeriCode: "446",
  },
  {
    country: "madagascar",
    alpha2: "mg",
    alpha3: "mdg",
    currencyNumeriCode: "450",
  },
  {
    country: "malawi",
    alpha2: "mw",
    alpha3: "mwi",
    currencyNumeriCode: "454",
  },
  {
    country: "malaysia",
    alpha2: "my",
    alpha3: "mys",
    currencyNumeriCode: "458",
  },
  {
    country: "maldives",
    alpha2: "mv",
    alpha3: "mdv",
    currencyNumeriCode: "462",
  },
  {
    country: "mali",
    alpha2: "ml",
    alpha3: "mli",
    currencyNumeriCode: "466",
  },
  {
    country: "malta",
    alpha2: "mt",
    alpha3: "mlt",
    currencyNumeriCode: "978",
  },
  {
    country: "marshall islands (the)",
    alpha2: "mh",
    alpha3: "mhl",
    currencyNumeriCode: "584",
  },
  {
    country: "martinique",
    alpha2: "mq",
    alpha3: "mtq",
    currencyNumeriCode: "474",
  },
  {
    country: "mauritania",
    alpha2: "mr",
    alpha3: "mrt",
    currencyNumeriCode: "478",
  },
  {
    country: "mauritius",
    alpha2: "mu",
    alpha3: "mus",
    currencyNumeriCode: "480",
  },
  {
    country: "mayotte",
    alpha2: "yt",
    alpha3: "myt",
    currencyNumeriCode: "175",
  },
  {
    country: "mexico",
    alpha2: "mx",
    alpha3: "mex",
    currencyNumeriCode: "484",
  },
  {
    country: "micronesia (federated states of)",
    alpha2: "fm",
    alpha3: "fsm",
    currencyNumeriCode: "583",
  },
  {
    country: "moldova (the republic of)",
    alpha2: "md",
    alpha3: "mda",
    currencyNumeriCode: "498",
  },
  {
    country: "monaco",
    alpha2: "mc",
    alpha3: "mco",
    currencyNumeriCode: "492",
  },
  {
    country: "mongolia",
    alpha2: "mn",
    alpha3: "mng",
    currencyNumeriCode: "496",
  },
  {
    country: "montenegro",
    alpha2: "me",
    alpha3: "mne",
    currencyNumeriCode: "499",
  },
  {
    country: "montserrat",
    alpha2: "ms",
    alpha3: "msr",
    currencyNumeriCode: "500",
  },
  {
    country: "morocco",
    alpha2: "ma",
    alpha3: "mar",
    currencyNumeriCode: "504",
  },
  {
    country: "mozambique",
    alpha2: "mz",
    alpha3: "moz",
    currencyNumeriCode: "508",
  },
  {
    country: "myanmar",
    alpha2: "mm",
    alpha3: "mmr",
    currencyNumeriCode: "104",
  },
  {
    country: "namibia",
    alpha2: "na",
    alpha3: "nam",
    currencyNumeriCode: "516",
  },
  {
    country: "nauru",
    alpha2: "nr",
    alpha3: "nru",
    currencyNumeriCode: "520",
  },
  {
    country: "nepal",
    alpha2: "np",
    alpha3: "npl",
    currencyNumeriCode: "524",
  },
  {
    country: "netherlands",
    alpha2: "nl",
    alpha3: "nld",
    currencyNumeriCode: "978",
  },
  {
    country: "new caledonia",
    alpha2: "nc",
    alpha3: "ncl",
    currencyNumeriCode: "540",
  },
  {
    country: "new zealand",
    alpha2: "nz",
    alpha3: "nzl",
    currencyNumeriCode: "554",
  },
  {
    country: "nicaragua",
    alpha2: "ni",
    alpha3: "nic",
    currencyNumeriCode: "558",
  },
  {
    country: "niger (the)",
    alpha2: "ne",
    alpha3: "ner",
    currencyNumeriCode: "562",
  },
  {
    country: "nigeria",
    alpha2: "ng",
    alpha3: "nga",
    currencyNumeriCode: "566",
  },
  {
    country: "niue",
    alpha2: "nu",
    alpha3: "niu",
    currencyNumeriCode: "570",
  },
  {
    country: "norfolk island",
    alpha2: "nf",
    alpha3: "nfk",
    currencyNumeriCode: "574",
  },
  {
    country: "northern mariana islands (the)",
    alpha2: "mp",
    alpha3: "mnp",
    currencyNumeriCode: "580",
  },
  {
    country: "norway",
    alpha2: "no",
    alpha3: "nor",
    currencyNumeriCode: "578",
  },
  {
    country: "oman",
    alpha2: "om",
    alpha3: "omn",
    currencyNumeriCode: "512",
  },
  {
    country: "pakistan",
    alpha2: "pk",
    alpha3: "pak",
    currencyNumeriCode: "586",
  },
  {
    country: "palau",
    alpha2: "pw",
    alpha3: "plw",
    currencyNumeriCode: "585",
  },
  {
    country: "palestine, state of",
    alpha2: "ps",
    alpha3: "pse",
    currencyNumeriCode: "275",
  },
  {
    country: "panama",
    alpha2: "pa",
    alpha3: "pan",
    currencyNumeriCode: "591",
  },
  {
    country: "papua new guinea",
    alpha2: "pg",
    alpha3: "png",
    currencyNumeriCode: "598",
  },
  {
    country: "paraguay",
    alpha2: "py",
    alpha3: "pry",
    currencyNumeriCode: "600",
  },
  {
    country: "peru",
    alpha2: "pe",
    alpha3: "per",
    currencyNumeriCode: "604",
  },
  {
    country: "philippines (the)",
    alpha2: "ph",
    alpha3: "phl",
    currencyNumeriCode: "608",
  },
  {
    country: "pitcairn",
    alpha2: "pn",
    alpha3: "pcn",
    currencyNumeriCode: "612",
  },
  {
    country: "poland",
    alpha2: "pl",
    alpha3: "pol",
    currencyNumeriCode: "985",
  },
  {
    country: "portugal",
    alpha2: "pt",
    alpha3: "prt",
    currencyNumeriCode: "978",
  },
  {
    country: "puerto rico",
    alpha2: "pr",
    alpha3: "pri",
    currencyNumeriCode: "630",
  },
  {
    country: "qatar",
    alpha2: "qa",
    alpha3: "qat",
    currencyNumeriCode: "634",
  },
  {
    country: "republic of north macedonia",
    alpha2: "mk",
    alpha3: "mkd",
    currencyNumeriCode: "807",
  },
  {
    country: "romania",
    alpha2: "ro",
    alpha3: "rou",
    currencyNumeriCode: "946",
  },
  {
    country: "russian federation (the)",
    alpha2: "ru",
    alpha3: "rus",
    currencyNumeriCode: "643",
  },
  {
    country: "rwanda",
    alpha2: "rw",
    alpha3: "rwa",
    currencyNumeriCode: "646",
  },
  {
    country: "réunion",
    alpha2: "re",
    alpha3: "reu",
    currencyNumeriCode: "638",
  },
  {
    country: "saint barthélemy",
    alpha2: "bl",
    alpha3: "blm",
    currencyNumeriCode: "652",
  },
  {
    country: "saint helena, ascension and tristan da cunha",
    alpha2: "sh",
    alpha3: "shn",
    currencyNumeriCode: "654",
  },
  {
    country: "saint kitts and nevis",
    alpha2: "kn",
    alpha3: "kna",
    currencyNumeriCode: "659",
  },
  {
    country: "saint lucia",
    alpha2: "lc",
    alpha3: "lca",
    currencyNumeriCode: "662",
  },
  {
    country: "saint martin (french part)",
    alpha2: "mf",
    alpha3: "maf",
    currencyNumeriCode: "663",
  },
  {
    country: "saint pierre and miquelon",
    alpha2: "pm",
    alpha3: "spm",
    currencyNumeriCode: "666",
  },
  {
    country: "saint vincent and the grenadines",
    alpha2: "vc",
    alpha3: "vct",
    currencyNumeriCode: "670",
  },
  {
    country: "samoa",
    alpha2: "ws",
    alpha3: "wsm",
    currencyNumeriCode: "882",
  },
  {
    country: "san marino",
    alpha2: "sm",
    alpha3: "smr",
    currencyNumeriCode: "674",
  },
  {
    country: "sao tome and principe",
    alpha2: "st",
    alpha3: "stp",
    currencyNumeriCode: "678",
  },
  {
    country: "saudi arabia",
    alpha2: "sa",
    alpha3: "sau",
    currencyNumeriCode: "682",
  },
  {
    country: "senegal",
    alpha2: "sn",
    alpha3: "sen",
    currencyNumeriCode: "686",
  },
  {
    country: "serbia",
    alpha2: "rs",
    alpha3: "srb",
    currencyNumeriCode: "941",
  },
  {
    country: "seychelles",
    alpha2: "sc",
    alpha3: "syc",
    currencyNumeriCode: "690",
  },
  {
    country: "sierra leone",
    alpha2: "sl",
    alpha3: "sle",
    currencyNumeriCode: "694",
  },
  {
    country: "singapore",
    alpha2: "sg",
    alpha3: "sgp",
    currencyNumeriCode: "702",
  },
  {
    country: "sint maarten (dutch part)",
    alpha2: "sx",
    alpha3: "sxm",
    currencyNumeriCode: "534",
  },
  {
    country: "slovakia",
    alpha2: "sk",
    alpha3: "svk",
    currencyNumeriCode: "978",
  },
  {
    country: "slovenia",
    alpha2: "si",
    alpha3: "svn",
    currencyNumeriCode: "978",
  },
  {
    country: "solomon islands",
    alpha2: "sb",
    alpha3: "slb",
    currencyNumeriCode: "090",
  },
  {
    country: "somalia",
    alpha2: "so",
    alpha3: "som",
    currencyNumeriCode: "706",
  },
  {
    country: "south africa",
    alpha2: "za",
    alpha3: "zaf",
    currencyNumeriCode: "710",
  },
  {
    country: "south georgia and the south sandwich islands",
    alpha2: "gs",
    alpha3: "sgs",
    currencyNumeriCode: "239",
  },
  {
    country: "south sudan",
    alpha2: "ss",
    alpha3: "ssd",
    currencyNumeriCode: "728",
  },
  {
    country: "spain",
    alpha2: "es",
    alpha3: "esp",
    currencyNumeriCode: "978",
  },
  {
    country: "sri lanka",
    alpha2: "lk",
    alpha3: "lka",
    currencyNumeriCode: "144",
  },
  {
    country: "sudan (the)",
    alpha2: "sd",
    alpha3: "sdn",
    currencyNumeriCode: "729",
  },
  {
    country: "suriname",
    alpha2: "sr",
    alpha3: "sur",
    currencyNumeriCode: "740",
  },
  {
    country: "svalbard and jan mayen",
    alpha2: "sj",
    alpha3: "sjm",
    currencyNumeriCode: "744",
  },
  {
    country: "sweden",
    alpha2: "se",
    alpha3: "swe",
    currencyNumeriCode: "752",
  },
  {
    country: "switzerland",
    alpha2: "ch",
    alpha3: "che",
    currencyNumeriCode: "756",
  },
  {
    country: "syrian arab republic",
    alpha2: "sy",
    alpha3: "syr",
    currencyNumeriCode: "760",
  },
  {
    country: "taiwan (province of china)",
    alpha2: "tw",
    alpha3: "twn",
    currencyNumeriCode: "158",
  },
  {
    country: "tajikistan",
    alpha2: "tj",
    alpha3: "tjk",
    currencyNumeriCode: "762",
  },
  {
    country: "tanzania, united republic of",
    alpha2: "tz",
    alpha3: "tza",
    currencyNumeriCode: "834",
  },
  {
    country: "thailand",
    alpha2: "th",
    alpha3: "tha",
    currencyNumeriCode: "764",
  },
  {
    country: "timor-leste",
    alpha2: "tl",
    alpha3: "tls",
    currencyNumeriCode: "626",
  },
  {
    country: "togo",
    alpha2: "tg",
    alpha3: "tgo",
    currencyNumeriCode: "768",
  },
  {
    country: "tokelau",
    alpha2: "tk",
    alpha3: "tkl",
    currencyNumeriCode: "772",
  },
  {
    country: "tonga",
    alpha2: "to",
    alpha3: "ton",
    currencyNumeriCode: "776",
  },
  {
    country: "trinidad and tobago",
    alpha2: "tt",
    alpha3: "tto",
    currencyNumeriCode: "780",
  },
  {
    country: "tunisia",
    alpha2: "tn",
    alpha3: "tun",
    currencyNumeriCode: "788",
  },
  {
    country: "turkey",
    alpha2: "tr",
    alpha3: "tur",
    currencyNumeriCode: "949",
  },
  {
    country: "turkmenistan",
    alpha2: "tm",
    alpha3: "tkm",
    currencyNumeriCode: "934",
  },
  {
    country: "turks and caicos islands (the)",
    alpha2: "tc",
    alpha3: "tca",
    currencyNumeriCode: "796",
  },
  {
    country: "tuvalu",
    alpha2: "tv",
    alpha3: "tuv",
    currencyNumeriCode: "798",
  },
  {
    country: "uganda",
    alpha2: "ug",
    alpha3: "uga",
    currencyNumeriCode: "800",
  },
  {
    country: "ukraine",
    alpha2: "ua",
    alpha3: "ukr",
    currencyNumeriCode: "980",
  },
  {
    country: "united arab emirates (the)",
    alpha2: "ae",
    alpha3: "are",
    currencyNumeriCode: "784",
  },
  {
    country: "united kingdom of great britain and northern ireland (the)",
    alpha2: "gb",
    alpha3: "gbr",
    currencyNumeriCode: "826",
  },
  {
    country: "united states minor outlying islands (the)",
    alpha2: "um",
    alpha3: "umi",
    currencyNumeriCode: "581",
  },
  {
    country: "united states of america (the)",
    alpha2: "us",
    alpha3: "usa",
    currencyNumeriCode: "840",
  },
  {
    country: "uruguay",
    alpha2: "uy",
    alpha3: "ury",
    currencyNumeriCode: "858",
  },
  {
    country: "uzbekistan",
    alpha2: "uz",
    alpha3: "uzb",
    currencyNumeriCode: "860",
  },
  {
    country: "vanuatu",
    alpha2: "vu",
    alpha3: "vut",
    currencyNumeriCode: "548",
  },
  {
    country: "venezuela (bolivarian republic of)",
    alpha2: "ve",
    alpha3: "ven",
    currencyNumeriCode: "862",
  },
  {
    country: "viet nam",
    alpha2: "vn",
    alpha3: "vnm",
    currencyNumeriCode: "704",
  },
  {
    country: "virgin islands (british)",
    alpha2: "vg",
    alpha3: "vgb",
    currencyNumeriCode: "092",
  },
  {
    country: "virgin islands (u.s.)",
    alpha2: "vi",
    alpha3: "vir",
    currencyNumeriCode: "850",
  },
  {
    country: "wallis and futuna",
    alpha2: "wf",
    alpha3: "wlf",
    currencyNumeriCode: "876",
  },
  {
    country: "western sahara",
    alpha2: "eh",
    alpha3: "esh",
    currencyNumeriCode: "732",
  },
  {
    country: "yemen",
    alpha2: "ye",
    alpha3: "yem",
    currencyNumeriCode: "886",
  },
  {
    country: "zambia",
    alpha2: "zm",
    alpha3: "zmb",
    currencyNumeriCode: "894",
  },
  {
    country: "zimbabwe",
    alpha2: "zw",
    alpha3: "zwe",
    currencyNumeriCode: "716",
  },
  {
    country: "åland islands",
    alpha2: "ax",
    alpha3: "ala",
    currencyNumeriCode: "978",
  },
];
