const countriesArray = [
  {
    country: "albania",
    code: "all",
    numericCode: "008",
    currencyName: "lek",
  },
  {
    country: "algeria",
    code: "dzd",
    numericCode: "012",
    currencyName: "algerian dinar",
  },
  {
    country: "american samoa",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "andorra",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "angola",
    code: "aoa",
    numericCode: "973",
    currencyName: "kwanza",
  },
  {
    country: "anguilla",
    code: "xcd",
    numericCode: "951",
    currencyName: "east caribbean dollar",
  },
  {
    country: "antarctica",
    code: "",
    numericCode: "",
    currencyName: "no universal currency",
  },
  {
    country: "antigua and barbuda",
    code: "xcd",
    numericCode: "951",
    currencyName: "east caribbean dollar",
  },
  {
    country: "argentina",
    code: "ars",
    numericCode: "032",
    currencyName: "argentine peso",
  },
  {
    country: "armenia",
    code: "amd",
    numericCode: "051",
    currencyName: "armenian dram",
  },
  {
    country: "aruba",
    code: "awg",
    numericCode: "533",
    currencyName: "aruban florin",
  },
  {
    country: "australia",
    code: "aud",
    numericCode: "036",
    currencyName: "australian dollar",
  },
  {
    country: "austria",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "azerbaijan",
    code: "azn",
    numericCode: "944",
    currencyName: "azerbaijanian manat",
  },
  {
    country: "bahamas (the)",
    code: "bsd",
    numericCode: "044",
    currencyName: "bahamian dollar",
  },
  {
    country: "bahrain",
    code: "bhd",
    numericCode: "048",
    currencyName: "bahraini dinar",
  },
  {
    country: "bangladesh",
    code: "bdt",
    numericCode: "050",
    currencyName: "taka",
  },
  {
    country: "barbados",
    code: "bbd",
    numericCode: "052",
    currencyName: "barbados dollar",
  },
  {
    country: "belarus",
    code: "byn",
    numericCode: "933",
    currencyName: "belarussian ruble",
  },
  {
    country: "belgium",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "belize",
    code: "bzd",
    numericCode: "084",
    currencyName: "belize dollar",
  },
  {
    country: "benin",
    code: "xof",
    numericCode: "952",
    currencyName: "cfa franc bceao",
  },
  {
    country: "bermuda",
    code: "bmd",
    numericCode: "060",
    currencyName: "bermudian dollar",
  },
  {
    country: "bhutan",
    code: "btn",
    numericCode: "064",
    currencyName: "ngultrum",
  },
  {
    country: "bhutan",
    code: "inr",
    numericCode: "356",
    currencyName: "indian rupee",
  },
  {
    country: "bolivia (plurinational state of)",
    code: "bob",
    numericCode: "068",
    currencyName: "boliviano",
  },
  {
    country: "bolivia (plurinational state of)",
    code: "bov",
    numericCode: "984",
    currencyName: "mvdol",
  },
  {
    country: "bonaire, sint eustatius and saba",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "bosnia and herzegovina",
    code: "bam",
    numericCode: "977",
    currencyName: "convertible mark",
  },
  {
    country: "botswana",
    code: "bwp",
    numericCode: "072",
    currencyName: "pula",
  },
  {
    country: "bouvet island",
    code: "nok",
    numericCode: "578",
    currencyName: "norwegian krone",
  },
  {
    country: "brazil",
    code: "brl",
    numericCode: "986",
    currencyName: "brazilian real",
  },
  {
    country: "british indian ocean territory (the)",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "brunei darussalam",
    code: "bnd",
    numericCode: "096",
    currencyName: "brunei dollar",
  },
  {
    country: "bulgaria",
    code: "bgn",
    numericCode: "975",
    currencyName: "bulgarian lev",
  },
  {
    country: "burkina faso",
    code: "xof",
    numericCode: "952",
    currencyName: "cfa franc bceao",
  },
  {
    country: "burundi",
    code: "bif",
    numericCode: "108",
    currencyName: "burundi franc",
  },
  {
    country: "cabo verde",
    code: "cve",
    numericCode: "132",
    currencyName: "cabo verde escudo",
  },
  {
    country: "cambodia",
    code: "khr",
    numericCode: "116",
    currencyName: "riel",
  },
  {
    country: "cameroon",
    code: "xaf",
    numericCode: "950",
    currencyName: "cfa franc beac",
  },
  {
    country: "canada",
    code: "cad",
    numericCode: "124",
    currencyName: "canadian dollar",
  },
  {
    country: "cayman islands (the)",
    code: "kyd",
    numericCode: "136",
    currencyName: "cayman islands dollar",
  },
  {
    country: "central african republic (the)",
    code: "xaf",
    numericCode: "950",
    currencyName: "cfa franc beac",
  },
  {
    country: "chad",
    code: "xaf",
    numericCode: "950",
    currencyName: "cfa franc beac",
  },
  {
    country: "chile",
    code: "clf",
    numericCode: "990",
    currencyName: "unidad de fomento",
  },
  {
    country: "chile",
    code: "clp",
    numericCode: "152",
    currencyName: "chilean peso",
  },
  {
    country: "china",
    code: "cny",
    numericCode: "156",
    currencyName: "yuan renminbi",
  },
  {
    country: "christmas island",
    code: "aud",
    numericCode: "036",
    currencyName: "australian dollar",
  },
  {
    country: "cocos (keeling) islands (the)",
    code: "aud",
    numericCode: "036",
    currencyName: "australian dollar",
  },
  {
    country: "colombia",
    code: "cop",
    numericCode: "170",
    currencyName: "colombian peso",
  },
  {
    country: "colombia",
    code: "cou",
    numericCode: "970",
    currencyName: "unidad de valor real",
  },
  {
    country: "comoros (the)",
    code: "kmf",
    numericCode: "174",
    currencyName: "comoro franc",
  },
  {
    country: "congo (the democratic republic of the)",
    code: "cdf",
    numericCode: "976",
    currencyName: "congolese franc",
  },
  {
    country: "congo (the)",
    code: "xaf",
    numericCode: "950",
    currencyName: "cfa franc beac",
  },
  {
    country: "cook islands (the)",
    code: "nzd",
    numericCode: "554",
    currencyName: "new zealand dollar",
  },
  {
    country: "costa rica",
    code: "crc",
    numericCode: "188",
    currencyName: "costa rican colon",
  },
  {
    country: "croatia",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "cuba",
    code: "cuc",
    numericCode: "931",
    currencyName: "peso convertible",
  },
  {
    country: "cuba",
    code: "cup",
    numericCode: "192",
    currencyName: "cuban peso",
  },
  {
    country: "curaçao",
    code: "ang",
    numericCode: "532",
    currencyName: "netherlands antillean guilder",
  },
  {
    country: "cyprus",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "czech republic (the)",
    code: "czk",
    numericCode: "203",
    currencyName: "czech koruna",
  },
  {
    country: "côte d'ivoire",
    code: "xof",
    numericCode: "952",
    currencyName: "cfa franc bceao",
  },
  {
    country: "denmark",
    code: "dkk",
    numericCode: "208",
    currencyName: "danish krone",
  },
  {
    country: "djibouti",
    code: "djf",
    numericCode: "262",
    currencyName: "djibouti franc",
  },
  {
    country: "dominica",
    code: "xcd",
    numericCode: "951",
    currencyName: "east caribbean dollar",
  },
  {
    country: "dominican republic (the)",
    code: "dop",
    numericCode: "214",
    currencyName: "dominican peso",
  },
  {
    country: "ecuador",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "egypt",
    code: "egp",
    numericCode: "818",
    currencyName: "egyptian pound",
  },
  {
    country: "el salvador",
    code: "svc",
    numericCode: "222",
    currencyName: "el salvador colon",
  },
  {
    country: "el salvador",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "equatorial guinea",
    code: "xaf",
    numericCode: "950",
    currencyName: "cfa franc beac",
  },
  {
    country: "eritrea",
    code: "ern",
    numericCode: "232",
    currencyName: "nakfa",
  },
  {
    country: "estonia",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "ethiopia",
    code: "etb",
    numericCode: "230",
    currencyName: "ethiopian birr",
  },
  {
    country: "european union",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "falkland islands (the) [malvinas]",
    code: "fkp",
    numericCode: "238",
    currencyName: "falkland islands pound",
  },
  {
    country: "faroe islands (the)",
    code: "dkk",
    numericCode: "208",
    currencyName: "danish krone",
  },
  {
    country: "fiji",
    code: "fjd",
    numericCode: "242",
    currencyName: "fiji dollar",
  },
  {
    country: "finland",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "france",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "french guiana",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "french polynesia",
    code: "xpf",
    numericCode: "953",
    currencyName: "cfp franc",
  },
  {
    country: "french southern territories (the)",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "gabon",
    code: "xaf",
    numericCode: "950",
    currencyName: "cfa franc beac",
  },
  {
    country: "gambia (the)",
    code: "gmd",
    numericCode: "270",
    currencyName: "dalasi",
  },
  {
    country: "georgia",
    code: "gel",
    numericCode: "981",
    currencyName: "lari",
  },
  {
    country: "germany",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "ghana",
    code: "ghs",
    numericCode: "936",
    currencyName: "ghana cedi",
  },
  {
    country: "gibraltar",
    code: "gip",
    numericCode: "292",
    currencyName: "gibraltar pound",
  },
  {
    country: "greece",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "greenland",
    code: "dkk",
    numericCode: "208",
    currencyName: "danish krone",
  },
  {
    country: "grenada",
    code: "xcd",
    numericCode: "951",
    currencyName: "east caribbean dollar",
  },
  {
    country: "guadeloupe",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "guam",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "guatemala",
    code: "gtq",
    numericCode: "320",
    currencyName: "quetzal",
  },
  {
    country: "guernsey",
    code: "gbp",
    numericCode: "826",
    currencyName: "pound sterling",
  },
  {
    country: "guinea",
    code: "gnf",
    numericCode: "324",
    currencyName: "guinea franc",
  },
  {
    country: "guinea-bissau",
    code: "xof",
    numericCode: "952",
    currencyName: "cfa franc bceao",
  },
  {
    country: "guyana",
    code: "gyd",
    numericCode: "328",
    currencyName: "guyana dollar",
  },
  {
    country: "haiti",
    code: "htg",
    numericCode: "332",
    currencyName: "gourde",
  },
  {
    country: "haiti",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "heard island and mcdonald islands",
    code: "aud",
    numericCode: "036",
    currencyName: "australian dollar",
  },
  {
    country: "holy see (the)",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "honduras",
    code: "hnl",
    numericCode: "340",
    currencyName: "lempira",
  },
  {
    country: "hong kong",
    code: "hkd",
    numericCode: "344",
    currencyName: "hong kong dollar",
  },
  {
    country: "hungary",
    code: "huf",
    numericCode: "348",
    currencyName: "forint",
  },
  {
    country: "iceland",
    code: "isk",
    numericCode: "352",
    currencyName: "iceland krona",
  },
  {
    country: "india",
    code: "inr",
    numericCode: "356",
    currencyName: "indian rupee",
  },
  {
    country: "indonesia",
    code: "idr",
    numericCode: "360",
    currencyName: "rupiah",
  },
  {
    country: "international monetary fund (imf)",
    code: "xdr",
    numericCode: "960",
    currencyName: "sdr (special drawing right)",
  },
  {
    country: "iran (islamic republic of)",
    code: "irr",
    numericCode: "364",
    currencyName: "iranian rial",
  },
  {
    country: "iraq",
    code: "iqd",
    numericCode: "368",
    currencyName: "iraqi dinar",
  },
  {
    country: "ireland",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "isle of man",
    code: "gbp",
    numericCode: "826",
    currencyName: "pound sterling",
  },
  {
    country: "israel",
    code: "ils",
    numericCode: "376",
    currencyName: "new israeli sheqel",
  },
  {
    country: "italy",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "jamaica",
    code: "jmd",
    numericCode: "388",
    currencyName: "jamaican dollar",
  },
  {
    country: "japan",
    code: "jpy",
    numericCode: "392",
    currencyName: "yen",
  },
  {
    country: "jersey",
    code: "gbp",
    numericCode: "826",
    currencyName: "pound sterling",
  },
  {
    country: "jordan",
    code: "jod",
    numericCode: "400",
    currencyName: "jordanian dinar",
  },
  {
    country: "kazakhstan",
    code: "kzt",
    numericCode: "398",
    currencyName: "tenge",
  },
  {
    country: "kenya",
    code: "kes",
    numericCode: "404",
    currencyName: "kenyan shilling",
  },
  {
    country: "kiribati",
    code: "aud",
    numericCode: "036",
    currencyName: "australian dollar",
  },
  {
    country: "korea (the democratic people’s republic of)",
    code: "kpw",
    numericCode: "408",
    currencyName: "north korean won",
  },
  {
    country: "korea (the republic of)",
    code: "krw",
    numericCode: "410",
    currencyName: "won",
  },
  {
    country: "kuwait",
    code: "kwd",
    numericCode: "414",
    currencyName: "kuwaiti dinar",
  },
  {
    country: "kyrgyzstan",
    code: "kgs",
    numericCode: "417",
    currencyName: "som",
  },
  {
    country: "lao people’s democratic republic (the)",
    code: "lak",
    numericCode: "418",
    currencyName: "kip",
  },
  {
    country: "latvia",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "lebanon",
    code: "lbp",
    numericCode: "422",
    currencyName: "lebanese pound",
  },
  {
    country: "lesotho",
    code: "lsl",
    numericCode: "426",
    currencyName: "loti",
  },
  {
    country: "lesotho",
    code: "zar",
    numericCode: "710",
    currencyName: "rand",
  },
  {
    country: "liberia",
    code: "lrd",
    numericCode: "430",
    currencyName: "liberian dollar",
  },
  {
    country: "libya",
    code: "lyd",
    numericCode: "434",
    currencyName: "libyan dinar",
  },
  {
    country: "liechtenstein",
    code: "chf",
    numericCode: "756",
    currencyName: "swiss franc",
  },
  {
    country: "lithuania",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "luxembourg",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "macao",
    code: "mop",
    numericCode: "446",
    currencyName: "pataca",
  },
  {
    country: "madagascar",
    code: "mga",
    numericCode: "969",
    currencyName: "malagasy ariary",
  },
  {
    country: "malawi",
    code: "mwk",
    numericCode: "454",
    currencyName: "malawi kwacha",
  },
  {
    country: "malaysia",
    code: "myr",
    numericCode: "458",
    currencyName: "malaysian ringgit",
  },
  {
    country: "maldives",
    code: "mvr",
    numericCode: "462",
    currencyName: "rufiyaa",
  },
  {
    country: "mali",
    code: "xof",
    numericCode: "952",
    currencyName: "cfa franc bceao",
  },
  {
    country: "malta",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "marshall islands (the)",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "martinique",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "mauritania",
    code: "mru",
    numericCode: "929",
    currencyName: "ouguiya",
  },
  {
    country: "mauritius",
    code: "mur",
    numericCode: "480",
    currencyName: "mauritius rupee",
  },
  {
    country: "mayotte",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "member countries of the african development bank group",
    code: "xua",
    numericCode: "965",
    currencyName: "adb unit of account",
  },
  {
    country: "mexico",
    code: "mxn",
    numericCode: "484",
    currencyName: "mexican peso",
  },
  {
    country: "mexico",
    code: "mxv",
    numericCode: "979",
    currencyName: "mexican unidad de inversion (udi)",
  },
  {
    country: "micronesia (federated states of)",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "moldova (the republic of)",
    code: "mdl",
    numericCode: "498",
    currencyName: "moldovan leu",
  },
  {
    country: "monaco",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "mongolia",
    code: "mnt",
    numericCode: "496",
    currencyName: "tugrik",
  },
  {
    country: "montenegro",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "montserrat",
    code: "xcd",
    numericCode: "951",
    currencyName: "east caribbean dollar",
  },
  {
    country: "morocco",
    code: "mad",
    numericCode: "504",
    currencyName: "moroccan dirham",
  },
  {
    country: "mozambique",
    code: "mzn",
    numericCode: "943",
    currencyName: "mozambique metical",
  },
  {
    country: "myanmar",
    code: "mmk",
    numericCode: "104",
    currencyName: "kyat",
  },
  {
    country: "namibia",
    code: "nad",
    numericCode: "516",
    currencyName: "namibia dollar",
  },
  {
    country: "namibia",
    code: "zar",
    numericCode: "710",
    currencyName: "rand",
  },
  {
    country: "nauru",
    code: "aud",
    numericCode: "036",
    currencyName: "australian dollar",
  },
  {
    country: "nepal",
    code: "npr",
    numericCode: "524",
    currencyName: "nepalese rupee",
  },
  {
    country: "netherlands (the)",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "new caledonia",
    code: "xpf",
    numericCode: "953",
    currencyName: "cfp franc",
  },
  {
    country: "new zealand",
    code: "nzd",
    numericCode: "554",
    currencyName: "new zealand dollar",
  },
  {
    country: "nicaragua",
    code: "nio",
    numericCode: "558",
    currencyName: "cordoba oro",
  },
  {
    country: "niger (the)",
    code: "xof",
    numericCode: "952",
    currencyName: "cfa franc bceao",
  },
  {
    country: "nigeria",
    code: "ngn",
    numericCode: "566",
    currencyName: "naira",
  },
  {
    country: "niue",
    code: "nzd",
    numericCode: "554",
    currencyName: "new zealand dollar",
  },
  {
    country: "norfolk island",
    code: "aud",
    numericCode: "036",
    currencyName: "australian dollar",
  },
  {
    country: "northern mariana islands (the)",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "norway",
    code: "nok",
    numericCode: "578",
    currencyName: "norwegian krone",
  },
  {
    country: "oman",
    code: "omr",
    numericCode: "512",
    currencyName: "rial omani",
  },
  {
    country: "pakistan",
    code: "pkr",
    numericCode: "586",
    currencyName: "pakistan rupee",
  },
  {
    country: "palau",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "palestine, state of",
    code: "ils",
    numericCode: "376",
    currencyName: "new israeli sheqel",
  },
  {
    country: "panama",
    code: "pab",
    numericCode: "590",
    currencyName: "balboa",
  },
  {
    country: "panama",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "papua new guinea",
    code: "pgk",
    numericCode: "598",
    currencyName: "kina",
  },
  {
    country: "paraguay",
    code: "pyg",
    numericCode: "600",
    currencyName: "guarani",
  },
  {
    country: "peru",
    code: "pen",
    numericCode: "604",
    currencyName: "sol",
  },
  {
    country: "philippines (the)",
    code: "php",
    numericCode: "608",
    currencyName: "philippine peso",
  },
  {
    country: "pitcairn",
    code: "nzd",
    numericCode: "554",
    currencyName: "new zealand dollar",
  },
  {
    country: "poland",
    code: "pln",
    numericCode: "985",
    currencyName: "zloty",
  },
  {
    country: "portugal",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "puerto rico",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "qatar",
    code: "qar",
    numericCode: "634",
    currencyName: "qatari rial",
  },
  {
    country: "republic of north macedonia",
    code: "mkd",
    numericCode: "807",
    currencyName: "denar",
  },
  {
    country: "romania",
    code: "ron",
    numericCode: "946",
    currencyName: "romanian leu",
  },
  {
    country: "russian federation (the)",
    code: "rub",
    numericCode: "643",
    currencyName: "russian ruble",
  },
  {
    country: "rwanda",
    code: "rwf",
    numericCode: "646",
    currencyName: "rwanda franc",
  },
  {
    country: "réunion",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "saint barthélemy",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "saint helena, ascension and tristan da cunha",
    code: "shp",
    numericCode: "654",
    currencyName: "saint helena pound",
  },
  {
    country: "saint kitts and nevis",
    code: "xcd",
    numericCode: "951",
    currencyName: "east caribbean dollar",
  },
  {
    country: "saint lucia",
    code: "xcd",
    numericCode: "951",
    currencyName: "east caribbean dollar",
  },
  {
    country: "saint martin (french part)",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "saint pierre and miquelon",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "saint vincent and the grenadines",
    code: "xcd",
    numericCode: "951",
    currencyName: "east caribbean dollar",
  },
  {
    country: "samoa",
    code: "wst",
    numericCode: "882",
    currencyName: "tala",
  },
  {
    country: "san marino",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "sao tome and principe",
    code: "stn",
    numericCode: "930",
    currencyName: "dobra",
  },
  {
    country: "saudi arabia",
    code: "sar",
    numericCode: "682",
    currencyName: "saudi riyal",
  },
  {
    country: "senegal",
    code: "xof",
    numericCode: "952",
    currencyName: "cfa franc bceao",
  },
  {
    country: "serbia",
    code: "rsd",
    numericCode: "941",
    currencyName: "serbian dinar",
  },
  {
    country: "seychelles",
    code: "scr",
    numericCode: "690",
    currencyName: "seychelles rupee",
  },
  {
    country: "sierra leone",
    code: "sll",
    numericCode: "694",
    currencyName: "leone",
  },
  {
    country: "singapore",
    code: "sgd",
    numericCode: "702",
    currencyName: "singapore dollar",
  },
  {
    country: "sint maarten (dutch part)",
    code: "ang",
    numericCode: "532",
    currencyName: "netherlands antillean guilder",
  },
  {
    country: "slovakia",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "slovenia",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "solomon islands",
    code: "sbd",
    numericCode: "090",
    currencyName: "solomon islands dollar",
  },
  {
    country: "somalia",
    code: "sos",
    numericCode: "706",
    currencyName: "somali shilling",
  },
  {
    country: "south africa",
    code: "zar",
    numericCode: "710",
    currencyName: "rand",
  },
  {
    country: "south sudan",
    code: "ssp",
    numericCode: "728",
    currencyName: "south sudanese pound",
  },
  {
    country: "spain",
    code: "eur",
    numericCode: "978",
    currencyName: "euro",
  },
  {
    country: "sri lanka",
    code: "lkr",
    numericCode: "144",
    currencyName: "sri lanka rupee",
  },
  {
    country: "sudan (the)",
    code: "sdg",
    numericCode: "938",
    currencyName: "sudanese pound",
  },
  {
    country: "suriname",
    code: "srd",
    numericCode: "968",
    currencyName: "surinam dollar",
  },
  {
    country: "svalbard and jan mayen",
    code: "nok",
    numericCode: "578",
    currencyName: "norwegian krone",
  },
  {
    country: "sweden",
    code: "sek",
    numericCode: "752",
    currencyName: "swedish krona",
  },
  {
    country: "switzerland",
    code: "chf",
    numericCode: "756",
    currencyName: "swiss franc",
  },
  {
    country: "syrian arab republic",
    code: "syp",
    numericCode: "760",
    currencyName: "syrian pound",
  },
  {
    country: "taiwan (province of china)",
    code: "twd",
    numericCode: "901",
    currencyName: "new taiwan dollar",
  },
  {
    country: "tajikistan",
    code: "tjs",
    numericCode: "972",
    currencyName: "somoni",
  },
  {
    country: "tanzania, united republic of",
    code: "tzs",
    numericCode: "834",
    currencyName: "tanzanian shilling",
  },
  {
    country: "thailand",
    code: "thb",
    numericCode: "764",
    currencyName: "baht",
  },
  {
    country: "timor-leste",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "togo",
    code: "xof",
    numericCode: "952",
    currencyName: "cfa franc bceao",
  },
  {
    country: "tokelau",
    code: "nzd",
    numericCode: "554",
    currencyName: "new zealand dollar",
  },
  {
    country: "tonga",
    code: "top",
    numericCode: "776",
    currencyName: "pa’anga",
  },
  {
    country: "trinidad and tobago",
    code: "ttd",
    numericCode: "780",
    currencyName: "trinidad and tobago dollar",
  },
  {
    country: "tunisia",
    code: "tnd",
    numericCode: "788",
    currencyName: "tunisian dinar",
  },
  {
    country: "turkey",
    code: "try",
    numericCode: "949",
    currencyName: "turkish lira",
  },
  {
    country: "turkmenistan",
    code: "tmt",
    numericCode: "934",
    currencyName: "turkmenistan new manat",
  },
  {
    country: "turks and caicos islands (the)",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "tuvalu",
    code: "aud",
    numericCode: "036",
    currencyName: "australian dollar",
  },
  {
    country: "uganda",
    code: "ugx",
    numericCode: "800",
    currencyName: "uganda shilling",
  },
  {
    country: "ukraine",
    code: "uah",
    numericCode: "980",
    currencyName: "hryvnia",
  },
  {
    country: "united arab emirates (the)",
    code: "aed",
    numericCode: "784",
    currencyName: "uae dirham",
  },
  {
    country: "united kingdom of great britain and northern ireland (the)",
    code: "gbp",
    numericCode: "826",
    currencyName: "pound sterling",
  },
  {
    country: "united states minor outlying islands (the)",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "united states of america (the)",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "uruguay",
    code: "uyu",
    numericCode: "858",
    currencyName: "peso uruguayo",
  },
  {
    country: "uruguay",
    code: "uyi",
    numericCode: "940",
    currencyName: "uruguay peso en unidades indexadas (ui)",
  },
  {
    country: "uzbekistan",
    code: "uzs",
    numericCode: "860",
    currencyName: "uzbekistan sum",
  },
  {
    country: "vanuatu",
    code: "vuv",
    numericCode: "548",
    currencyName: "vatu",
  },
  {
    country: "venezuela (bolivarian republic of)",
    code: "ves",
    numericCode: "928",
    currencyName: "bolívar soberano",
  },
  {
    country: "viet nam",
    code: "vnd",
    numericCode: "704",
    currencyName: "dong",
  },
  {
    country: "virgin islands (british)",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "virgin islands (u.s.)",
    code: "usd",
    numericCode: "840",
    currencyName: "us dollar",
  },
  {
    country: "wallis and futuna",
    code: "xpf",
    numericCode: "953",
    currencyName: "cfp franc",
  },
  {
    country: "western sahara",
    code: "mad",
    numericCode: "504",
    currencyName: "moroccan dirham",
  },
  {
    country: "yemen",
    code: "yer",
    numericCode: "886",
    currencyName: "yemeni rial",
  },
  {
    country: "zambia",
    code: "zmw",
    numericCode: "967",
    currencyName: "zambian kwacha",
  },
  {
    country: "zimbabwe",
    code: "zwl",
    numericCode: "932",
    currencyName: "zimbabwe dollar",
  },
];
