// const listCurrencyIsoData = [
//   {
//     country: "afghanistan",
//     alpha2: "af",
//     alpha3: "afg",
//     currencyNumeriсCode: "004",
//   },
//   {
//     country: "albania",
//     alpha2: "al",
//     alpha3: "alb",
//     currencyNumeriсCode: "008",
//   },
//   {
//     country: "algeria",
//     alpha2: "dz",
//     alpha3: "dza",
//     currencyNumeriсCode: "012",
//   },
//   {
//     country: "american samoa",
//     alpha2: "as",
//     alpha3: "asm",
//     currencyNumeriсCode: "016",
//   },
//   {
//     country: "andorra",
//     alpha2: "ad",
//     alpha3: "and",
//     currencyNumeriсCode: "020",
//   },
//   {
//     country: "angola",
//     alpha2: "ao",
//     alpha3: "ago",
//     currencyNumeriсCode: "024",
//   },
//   {
//     country: "anguilla",
//     alpha2: "ai",
//     alpha3: "aia",
//     currencyNumeriсCode: "660",
//   },
//   {
//     country: "antarctica",
//     alpha2: "aq",
//     alpha3: "ata",
//     currencyNumeriсCode: "010",
//   },
//   {
//     country: "antigua and barbuda",
//     alpha2: "ag",
//     alpha3: "atg",
//     currencyNumeriсCode: "028",
//   },
//   {
//     country: "argentina",
//     alpha2: "ar",
//     alpha3: "arg",
//     currencyNumeriсCode: "032",
//   },
//   {
//     country: "armenia",
//     alpha2: "am",
//     alpha3: "arm",
//     currencyNumeriсCode: "051",
//   },
//   {
//     country: "aruba",
//     alpha2: "aw",
//     alpha3: "abw",
//     currencyNumeriсCode: "533",
//   },
//   {
//     country: "australia",
//     alpha2: "au",
//     alpha3: "aus",
//     currencyNumeriсCode: "036",
//   },
//   {
//     country: "austria",
//     alpha2: "at",
//     alpha3: "aut",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "azerbaijan",
//     alpha2: "az",
//     alpha3: "aze",
//     currencyNumeriсCode: "031",
//   },
//   {
//     country: "bahamas (the)",
//     alpha2: "bs",
//     alpha3: "bhs",
//     currencyNumeriсCode: "044",
//   },
//   {
//     country: "bahrain",
//     alpha2: "bh",
//     alpha3: "bhr",
//     currencyNumeriсCode: "048",
//   },
//   {
//     country: "bangladesh",
//     alpha2: "bd",
//     alpha3: "bgd",
//     currencyNumeriсCode: "050",
//   },
//   {
//     country: "barbados",
//     alpha2: "bb",
//     alpha3: "brb",
//     currencyNumeriсCode: "052",
//   },
//   {
//     country: "belarus",
//     alpha2: "by",
//     alpha3: "blr",
//     currencyNumeriсCode: "112",
//   },
//   {
//     country: "belgium",
//     alpha2: "be",
//     alpha3: "bel",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "belize",
//     alpha2: "bz",
//     alpha3: "blz",
//     currencyNumeriсCode: "084",
//   },
//   {
//     country: "benin",
//     alpha2: "bj",
//     alpha3: "ben",
//     currencyNumeriсCode: "204",
//   },
//   {
//     country: "bermuda",
//     alpha2: "bm",
//     alpha3: "bmu",
//     currencyNumeriсCode: "060",
//   },
//   {
//     country: "bhutan",
//     alpha2: "bt",
//     alpha3: "btn",
//     currencyNumeriсCode: "064",
//   },
//   {
//     country: "bolivia (plurinational state of)",
//     alpha2: "bo",
//     alpha3: "bol",
//     currencyNumeriсCode: "068",
//   },
//   {
//     country: "bonaire, sint eustatius and saba",
//     alpha2: "bq",
//     alpha3: "bes",
//     currencyNumeriсCode: "535",
//   },
//   {
//     country: "bosnia and herzegovina",
//     alpha2: "ba",
//     alpha3: "bih",
//     currencyNumeriсCode: "070",
//   },
//   {
//     country: "botswana",
//     alpha2: "bw",
//     alpha3: "bwa",
//     currencyNumeriсCode: "072",
//   },
//   {
//     country: "bouvet island",
//     alpha2: "bv",
//     alpha3: "bvt",
//     currencyNumeriсCode: "074",
//   },
//   {
//     country: "brazil",
//     alpha2: "br",
//     alpha3: "bra",
//     currencyNumeriсCode: "076",
//   },
//   {
//     country: "british indian ocean territory (the)",
//     alpha2: "io",
//     alpha3: "iot",
//     currencyNumeriсCode: "086",
//   },
//   {
//     country: "brunei darussalam",
//     alpha2: "bn",
//     alpha3: "brn",
//     currencyNumeriсCode: "096",
//   },
//   {
//     country: "bulgaria",
//     alpha2: "bg",
//     alpha3: "bgr",
//     currencyNumeriсCode: "100",
//   },
//   {
//     country: "burkina faso",
//     alpha2: "bf",
//     alpha3: "bfa",
//     currencyNumeriсCode: "854",
//   },
//   {
//     country: "burundi",
//     alpha2: "bi",
//     alpha3: "bdi",
//     currencyNumeriсCode: "108",
//   },
//   {
//     country: "cabo verde",
//     alpha2: "cv",
//     alpha3: "cpv",
//     currencyNumeriсCode: "132",
//   },
//   {
//     country: "cambodia",
//     alpha2: "kh",
//     alpha3: "khm",
//     currencyNumeriсCode: "116",
//   },
//   {
//     country: "cameroon",
//     alpha2: "cm",
//     alpha3: "cmr",
//     currencyNumeriсCode: "120",
//   },
//   {
//     country: "canada",
//     alpha2: "ca",
//     alpha3: "can",
//     currencyNumeriсCode: "124",
//   },
//   {
//     country: "cayman islands (the)",
//     alpha2: "ky",
//     alpha3: "cym",
//     currencyNumeriсCode: "136",
//   },
//   {
//     country: "central african republic (the)",
//     alpha2: "cf",
//     alpha3: "caf",
//     currencyNumeriсCode: "140",
//   },
//   {
//     country: "chad",
//     alpha2: "td",
//     alpha3: "tcd",
//     currencyNumeriсCode: "148",
//   },
//   {
//     country: "chile",
//     alpha2: "cl",
//     alpha3: "chl",
//     currencyNumeriсCode: "152",
//   },
//   {
//     country: "china",
//     alpha2: "cn",
//     alpha3: "chn",
//     currencyNumeriсCode: "156",
//   },
//   {
//     country: "christmas island",
//     alpha2: "cx",
//     alpha3: "cxr",
//     currencyNumeriсCode: "162",
//   },
//   {
//     country: "cocos (keeling) islands (the)",
//     alpha2: "cc",
//     alpha3: "cck",
//     currencyNumeriсCode: "166",
//   },
//   {
//     country: "colombia",
//     alpha2: "co",
//     alpha3: "col",
//     currencyNumeriсCode: "170",
//   },
//   {
//     country: "comoros (the)",
//     alpha2: "km",
//     alpha3: "com",
//     currencyNumeriсCode: "174",
//   },
//   {
//     country: "congo (the democratic republic of the)",
//     alpha2: "cd",
//     alpha3: "cod",
//     currencyNumeriсCode: "180",
//   },
//   {
//     country: "congo (the)",
//     alpha2: "cg",
//     alpha3: "cog",
//     currencyNumeriсCode: "178",
//   },
//   {
//     country: "cook islands (the)",
//     alpha2: "ck",
//     alpha3: "cok",
//     currencyNumeriсCode: "184",
//   },
//   {
//     country: "costa rica",
//     alpha2: "cr",
//     alpha3: "cri",
//     currencyNumeriсCode: "188",
//   },
//   {
//     country: "croatia",
//     alpha2: "hr",
//     alpha3: "hrv",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "cuba",
//     alpha2: "cu",
//     alpha3: "cub",
//     currencyNumeriсCode: "192",
//   },
//   {
//     country: "curaçao",
//     alpha2: "cw",
//     alpha3: "cuw",
//     currencyNumeriсCode: "531",
//   },
//   {
//     country: "cyprus",
//     alpha2: "cy",
//     alpha3: "cyp",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "czechia",
//     alpha2: "cz",
//     alpha3: "cze",
//     currencyNumeriсCode: "203",
//   },
//   {
//     country: "côte d'ivoire",
//     alpha2: "ci",
//     alpha3: "civ",
//     currencyNumeriсCode: "384",
//   },
//   {
//     country: "denmark",
//     alpha2: "dk",
//     alpha3: "dnk",
//     currencyNumeriсCode: "208",
//   },
//   {
//     country: "djibouti",
//     alpha2: "dj",
//     alpha3: "dji",
//     currencyNumeriсCode: "262",
//   },
//   {
//     country: "dominica",
//     alpha2: "dm",
//     alpha3: "dma",
//     currencyNumeriсCode: "212",
//   },
//   {
//     country: "dominican republic (the)",
//     alpha2: "do",
//     alpha3: "dom",
//     currencyNumeriсCode: "214",
//   },
//   {
//     country: "ecuador",
//     alpha2: "ec",
//     alpha3: "ecu",
//     currencyNumeriсCode: "218",
//   },
//   {
//     country: "egypt",
//     alpha2: "eg",
//     alpha3: "egy",
//     currencyNumeriсCode: "818",
//   },
//   {
//     country: "el salvador",
//     alpha2: "sv",
//     alpha3: "slv",
//     currencyNumeriсCode: "222",
//   },
//   {
//     country: "equatorial guinea",
//     alpha2: "gq",
//     alpha3: "gnq",
//     currencyNumeriсCode: "226",
//   },
//   {
//     country: "eritrea",
//     alpha2: "er",
//     alpha3: "eri",
//     currencyNumeriсCode: "232",
//   },
//   {
//     country: "estonia",
//     alpha2: "ee",
//     alpha3: "est",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "eswatini",
//     alpha2: "sz",
//     alpha3: "swz",
//     currencyNumeriсCode: "748",
//   },
//   {
//     country: "ethiopia",
//     alpha2: "et",
//     alpha3: "eth",
//     currencyNumeriсCode: "231",
//   },
//   {
//     country: "falkland islands (the) [malvinas]",
//     alpha2: "fk",
//     alpha3: "flk",
//     currencyNumeriсCode: "238",
//   },
//   {
//     country: "faroe islands (the)",
//     alpha2: "fo",
//     alpha3: "fro",
//     currencyNumeriсCode: "234",
//   },
//   {
//     country: "fiji",
//     alpha2: "fj",
//     alpha3: "fji",
//     currencyNumeriсCode: "242",
//   },
//   {
//     country: "finland",
//     alpha2: "fi",
//     alpha3: "fin",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "france",
//     alpha2: "fr",
//     alpha3: "fra",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "french guiana",
//     alpha2: "gf",
//     alpha3: "guf",
//     currencyNumeriсCode: "254",
//   },
//   {
//     country: "french polynesia",
//     alpha2: "pf",
//     alpha3: "pyf",
//     currencyNumeriсCode: "258",
//   },
//   {
//     country: "french southern territories (the)",
//     alpha2: "tf",
//     alpha3: "atf",
//     currencyNumeriсCode: "260",
//   },
//   {
//     country: "gabon",
//     alpha2: "ga",
//     alpha3: "gab",
//     currencyNumeriсCode: "266",
//   },
//   {
//     country: "gambia (the)",
//     alpha2: "gm",
//     alpha3: "gmb",
//     currencyNumeriсCode: "270",
//   },
//   {
//     country: "georgia",
//     alpha2: "ge",
//     alpha3: "geo",
//     currencyNumeriсCode: "268",
//   },
//   {
//     country: "germany",
//     alpha2: "de",
//     alpha3: "deu",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "ghana",
//     alpha2: "gh",
//     alpha3: "gha",
//     currencyNumeriсCode: "288",
//   },
//   {
//     country: "gibraltar",
//     alpha2: "gi",
//     alpha3: "gib",
//     currencyNumeriсCode: "292",
//   },
//   {
//     country: "greece",
//     alpha2: "gr",
//     alpha3: "grc",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "greenland",
//     alpha2: "gl",
//     alpha3: "grl",
//     currencyNumeriсCode: "304",
//   },
//   {
//     country: "grenada",
//     alpha2: "gd",
//     alpha3: "grd",
//     currencyNumeriсCode: "308",
//   },
//   {
//     country: "guadeloupe",
//     alpha2: "gp",
//     alpha3: "glp",
//     currencyNumeriсCode: "312",
//   },
//   {
//     country: "guam",
//     alpha2: "gu",
//     alpha3: "gum",
//     currencyNumeriсCode: "316",
//   },
//   {
//     country: "guatemala",
//     alpha2: "gt",
//     alpha3: "gtm",
//     currencyNumeriсCode: "320",
//   },
//   {
//     country: "guernsey",
//     alpha2: "gg",
//     alpha3: "ggy",
//     currencyNumeriсCode: "831",
//   },
//   {
//     country: "guinea",
//     alpha2: "gn",
//     alpha3: "gin",
//     currencyNumeriсCode: "324",
//   },
//   {
//     country: "guinea-bissau",
//     alpha2: "gw",
//     alpha3: "gnb",
//     currencyNumeriсCode: "624",
//   },
//   {
//     country: "guyana",
//     alpha2: "gy",
//     alpha3: "guy",
//     currencyNumeriсCode: "328",
//   },
//   {
//     country: "haiti",
//     alpha2: "ht",
//     alpha3: "hti",
//     currencyNumeriсCode: "332",
//   },
//   {
//     country: "heard island and mcdonald islands",
//     alpha2: "hm",
//     alpha3: "hmd",
//     currencyNumeriсCode: "334",
//   },
//   {
//     country: "holy see (the)",
//     alpha2: "va",
//     alpha3: "vat",
//     currencyNumeriсCode: "336",
//   },
//   {
//     country: "honduras",
//     alpha2: "hn",
//     alpha3: "hnd",
//     currencyNumeriсCode: "340",
//   },
//   {
//     country: "hong kong",
//     alpha2: "hk",
//     alpha3: "hkg",
//     currencyNumeriсCode: "344",
//   },
//   {
//     country: "hungary",
//     alpha2: "hu",
//     alpha3: "hun",
//     currencyNumeriсCode: "348",
//   },
//   {
//     country: "iceland",
//     alpha2: "is",
//     alpha3: "isl",
//     currencyNumeriсCode: "352",
//   },
//   {
//     country: "india",
//     alpha2: "in",
//     alpha3: "ind",
//     currencyNumeriсCode: "356",
//   },
//   {
//     country: "indonesia",
//     alpha2: "id",
//     alpha3: "idn",
//     currencyNumeriсCode: "360",
//   },
//   {
//     country: "iran (islamic republic of)",
//     alpha2: "ir",
//     alpha3: "irn",
//     currencyNumeriсCode: "364",
//   },
//   {
//     country: "iraq",
//     alpha2: "iq",
//     alpha3: "irq",
//     currencyNumeriсCode: "368",
//   },
//   {
//     country: "ireland",
//     alpha2: "ie",
//     alpha3: "irl",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "isle of man",
//     alpha2: "im",
//     alpha3: "imn",
//     currencyNumeriсCode: "833",
//   },
//   {
//     country: "israel",
//     alpha2: "il",
//     alpha3: "isr",
//     currencyNumeriсCode: "376",
//   },
//   {
//     country: "italy",
//     alpha2: "it",
//     alpha3: "ita",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "jamaica",
//     alpha2: "jm",
//     alpha3: "jam",
//     currencyNumeriсCode: "388",
//   },
//   {
//     country: "japan",
//     alpha2: "jp",
//     alpha3: "jpn",
//     currencyNumeriсCode: "392",
//   },
//   {
//     country: "jersey",
//     alpha2: "je",
//     alpha3: "jey",
//     currencyNumeriсCode: "832",
//   },
//   {
//     country: "jordan",
//     alpha2: "jo",
//     alpha3: "jor",
//     currencyNumeriсCode: "400",
//   },
//   {
//     country: "kazakhstan",
//     alpha2: "kz",
//     alpha3: "kaz",
//     currencyNumeriсCode: "398",
//   },
//   {
//     country: "kenya",
//     alpha2: "ke",
//     alpha3: "ken",
//     currencyNumeriсCode: "404",
//   },
//   {
//     country: "kiribati",
//     alpha2: "ki",
//     alpha3: "kir",
//     currencyNumeriсCode: "296",
//   },
//   {
//     country: "korea (the democratic people's republic of)",
//     alpha2: "kp",
//     alpha3: "prk",
//     currencyNumeriсCode: "408",
//   },
//   {
//     country: "korea (the republic of)",
//     alpha2: "kr",
//     alpha3: "kor",
//     currencyNumeriсCode: "410",
//   },
//   {
//     country: "kuwait",
//     alpha2: "kw",
//     alpha3: "kwt",
//     currencyNumeriсCode: "414",
//   },
//   {
//     country: "kyrgyzstan",
//     alpha2: "kg",
//     alpha3: "kgz",
//     currencyNumeriсCode: "417",
//   },
//   {
//     country: "lao people's democratic republic (the)",
//     alpha2: "la",
//     alpha3: "lao",
//     currencyNumeriсCode: "418",
//   },
//   {
//     country: "latvia",
//     alpha2: "lv",
//     alpha3: "lva",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "lebanon",
//     alpha2: "lb",
//     alpha3: "lbn",
//     currencyNumeriсCode: "422",
//   },
//   {
//     country: "lesotho",
//     alpha2: "ls",
//     alpha3: "lso",
//     currencyNumeriсCode: "426",
//   },
//   {
//     country: "liberia",
//     alpha2: "lr",
//     alpha3: "lbr",
//     currencyNumeriсCode: "430",
//   },
//   {
//     country: "libya",
//     alpha2: "ly",
//     alpha3: "lby",
//     currencyNumeriсCode: "434",
//   },
//   {
//     country: "liechtenstein",
//     alpha2: "li",
//     alpha3: "lie",
//     currencyNumeriсCode: "438",
//   },
//   {
//     country: "lithuania",
//     alpha2: "lt",
//     alpha3: "ltu",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "luxembourg",
//     alpha2: "lu",
//     alpha3: "lux",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "macao",
//     alpha2: "mo",
//     alpha3: "mac",
//     currencyNumeriсCode: "446",
//   },
//   {
//     country: "madagascar",
//     alpha2: "mg",
//     alpha3: "mdg",
//     currencyNumeriсCode: "450",
//   },
//   {
//     country: "malawi",
//     alpha2: "mw",
//     alpha3: "mwi",
//     currencyNumeriсCode: "454",
//   },
//   {
//     country: "malaysia",
//     alpha2: "my",
//     alpha3: "mys",
//     currencyNumeriсCode: "458",
//   },
//   {
//     country: "maldives",
//     alpha2: "mv",
//     alpha3: "mdv",
//     currencyNumeriсCode: "462",
//   },
//   {
//     country: "mali",
//     alpha2: "ml",
//     alpha3: "mli",
//     currencyNumeriсCode: "466",
//   },
//   {
//     country: "malta",
//     alpha2: "mt",
//     alpha3: "mlt",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "marshall islands (the)",
//     alpha2: "mh",
//     alpha3: "mhl",
//     currencyNumeriсCode: "584",
//   },
//   {
//     country: "martinique",
//     alpha2: "mq",
//     alpha3: "mtq",
//     currencyNumeriсCode: "474",
//   },
//   {
//     country: "mauritania",
//     alpha2: "mr",
//     alpha3: "mrt",
//     currencyNumeriсCode: "478",
//   },
//   {
//     country: "mauritius",
//     alpha2: "mu",
//     alpha3: "mus",
//     currencyNumeriсCode: "480",
//   },
//   {
//     country: "mayotte",
//     alpha2: "yt",
//     alpha3: "myt",
//     currencyNumeriсCode: "175",
//   },
//   {
//     country: "mexico",
//     alpha2: "mx",
//     alpha3: "mex",
//     currencyNumeriсCode: "484",
//   },
//   {
//     country: "micronesia (federated states of)",
//     alpha2: "fm",
//     alpha3: "fsm",
//     currencyNumeriсCode: "583",
//   },
//   {
//     country: "moldova (the republic of)",
//     alpha2: "md",
//     alpha3: "mda",
//     currencyNumeriсCode: "498",
//   },
//   {
//     country: "monaco",
//     alpha2: "mc",
//     alpha3: "mco",
//     currencyNumeriсCode: "492",
//   },
//   {
//     country: "mongolia",
//     alpha2: "mn",
//     alpha3: "mng",
//     currencyNumeriсCode: "496",
//   },
//   {
//     country: "montenegro",
//     alpha2: "me",
//     alpha3: "mne",
//     currencyNumeriсCode: "499",
//   },
//   {
//     country: "montserrat",
//     alpha2: "ms",
//     alpha3: "msr",
//     currencyNumeriсCode: "500",
//   },
//   {
//     country: "morocco",
//     alpha2: "ma",
//     alpha3: "mar",
//     currencyNumeriсCode: "504",
//   },
//   {
//     country: "mozambique",
//     alpha2: "mz",
//     alpha3: "moz",
//     currencyNumeriсCode: "508",
//   },
//   {
//     country: "myanmar",
//     alpha2: "mm",
//     alpha3: "mmr",
//     currencyNumeriсCode: "104",
//   },
//   {
//     country: "namibia",
//     alpha2: "na",
//     alpha3: "nam",
//     currencyNumeriсCode: "516",
//   },
//   {
//     country: "nauru",
//     alpha2: "nr",
//     alpha3: "nru",
//     currencyNumeriсCode: "520",
//   },
//   {
//     country: "nepal",
//     alpha2: "np",
//     alpha3: "npl",
//     currencyNumeriсCode: "524",
//   },
//   {
//     country: "netherlands",
//     alpha2: "nl",
//     alpha3: "nld",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "new caledonia",
//     alpha2: "nc",
//     alpha3: "ncl",
//     currencyNumeriсCode: "540",
//   },
//   {
//     country: "new zealand",
//     alpha2: "nz",
//     alpha3: "nzl",
//     currencyNumeriсCode: "554",
//   },
//   {
//     country: "nicaragua",
//     alpha2: "ni",
//     alpha3: "nic",
//     currencyNumeriсCode: "558",
//   },
//   {
//     country: "niger (the)",
//     alpha2: "ne",
//     alpha3: "ner",
//     currencyNumeriсCode: "562",
//   },
//   {
//     country: "nigeria",
//     alpha2: "ng",
//     alpha3: "nga",
//     currencyNumeriсCode: "566",
//   },
//   {
//     country: "niue",
//     alpha2: "nu",
//     alpha3: "niu",
//     currencyNumeriсCode: "570",
//   },
//   {
//     country: "norfolk island",
//     alpha2: "nf",
//     alpha3: "nfk",
//     currencyNumeriсCode: "574",
//   },
//   {
//     country: "northern mariana islands (the)",
//     alpha2: "mp",
//     alpha3: "mnp",
//     currencyNumeriсCode: "580",
//   },
//   {
//     country: "norway",
//     alpha2: "no",
//     alpha3: "nor",
//     currencyNumeriсCode: "578",
//   },
//   {
//     country: "oman",
//     alpha2: "om",
//     alpha3: "omn",
//     currencyNumeriсCode: "512",
//   },
//   {
//     country: "pakistan",
//     alpha2: "pk",
//     alpha3: "pak",
//     currencyNumeriсCode: "586",
//   },
//   {
//     country: "palau",
//     alpha2: "pw",
//     alpha3: "plw",
//     currencyNumeriсCode: "585",
//   },
//   {
//     country: "palestine, state of",
//     alpha2: "ps",
//     alpha3: "pse",
//     currencyNumeriсCode: "275",
//   },
//   {
//     country: "panama",
//     alpha2: "pa",
//     alpha3: "pan",
//     currencyNumeriсCode: "591",
//   },
//   {
//     country: "papua new guinea",
//     alpha2: "pg",
//     alpha3: "png",
//     currencyNumeriсCode: "598",
//   },
//   {
//     country: "paraguay",
//     alpha2: "py",
//     alpha3: "pry",
//     currencyNumeriсCode: "600",
//   },
//   {
//     country: "peru",
//     alpha2: "pe",
//     alpha3: "per",
//     currencyNumeriсCode: "604",
//   },
//   {
//     country: "philippines (the)",
//     alpha2: "ph",
//     alpha3: "phl",
//     currencyNumeriсCode: "608",
//   },
//   {
//     country: "pitcairn",
//     alpha2: "pn",
//     alpha3: "pcn",
//     currencyNumeriсCode: "612",
//   },
//   {
//     country: "poland",
//     alpha2: "pl",
//     alpha3: "pol",
//     currencyNumeriсCode: "985",
//   },
//   {
//     country: "portugal",
//     alpha2: "pt",
//     alpha3: "prt",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "puerto rico",
//     alpha2: "pr",
//     alpha3: "pri",
//     currencyNumeriсCode: "630",
//   },
//   {
//     country: "qatar",
//     alpha2: "qa",
//     alpha3: "qat",
//     currencyNumeriсCode: "634",
//   },
//   {
//     country: "republic of north macedonia",
//     alpha2: "mk",
//     alpha3: "mkd",
//     currencyNumeriсCode: "807",
//   },
//   {
//     country: "romania",
//     alpha2: "ro",
//     alpha3: "rou",
//     currencyNumeriсCode: "946",
//   },
//   {
//     country: "russian federation (the)",
//     alpha2: "ru",
//     alpha3: "rus",
//     currencyNumeriсCode: "643",
//   },
//   {
//     country: "rwanda",
//     alpha2: "rw",
//     alpha3: "rwa",
//     currencyNumeriсCode: "646",
//   },
//   {
//     country: "réunion",
//     alpha2: "re",
//     alpha3: "reu",
//     currencyNumeriсCode: "638",
//   },
//   {
//     country: "saint barthélemy",
//     alpha2: "bl",
//     alpha3: "blm",
//     currencyNumeriсCode: "652",
//   },
//   {
//     country: "saint helena, ascension and tristan da cunha",
//     alpha2: "sh",
//     alpha3: "shn",
//     currencyNumeriсCode: "654",
//   },
//   {
//     country: "saint kitts and nevis",
//     alpha2: "kn",
//     alpha3: "kna",
//     currencyNumeriсCode: "659",
//   },
//   {
//     country: "saint lucia",
//     alpha2: "lc",
//     alpha3: "lca",
//     currencyNumeriсCode: "662",
//   },
//   {
//     country: "saint martin (french part)",
//     alpha2: "mf",
//     alpha3: "maf",
//     currencyNumeriсCode: "663",
//   },
//   {
//     country: "saint pierre and miquelon",
//     alpha2: "pm",
//     alpha3: "spm",
//     currencyNumeriсCode: "666",
//   },
//   {
//     country: "saint vincent and the grenadines",
//     alpha2: "vc",
//     alpha3: "vct",
//     currencyNumeriсCode: "670",
//   },
//   {
//     country: "samoa",
//     alpha2: "ws",
//     alpha3: "wsm",
//     currencyNumeriсCode: "882",
//   },
//   {
//     country: "san marino",
//     alpha2: "sm",
//     alpha3: "smr",
//     currencyNumeriсCode: "674",
//   },
//   {
//     country: "sao tome and principe",
//     alpha2: "st",
//     alpha3: "stp",
//     currencyNumeriсCode: "678",
//   },
//   {
//     country: "saudi arabia",
//     alpha2: "sa",
//     alpha3: "sau",
//     currencyNumeriсCode: "682",
//   },
//   {
//     country: "senegal",
//     alpha2: "sn",
//     alpha3: "sen",
//     currencyNumeriсCode: "686",
//   },
//   {
//     country: "serbia",
//     alpha2: "rs",
//     alpha3: "srb",
//     currencyNumeriсCode: "941",
//   },
//   {
//     country: "seychelles",
//     alpha2: "sc",
//     alpha3: "syc",
//     currencyNumeriсCode: "690",
//   },
//   {
//     country: "sierra leone",
//     alpha2: "sl",
//     alpha3: "sle",
//     currencyNumeriсCode: "694",
//   },
//   {
//     country: "singapore",
//     alpha2: "sg",
//     alpha3: "sgp",
//     currencyNumeriсCode: "702",
//   },
//   {
//     country: "sint maarten (dutch part)",
//     alpha2: "sx",
//     alpha3: "sxm",
//     currencyNumeriсCode: "534",
//   },
//   {
//     country: "slovakia",
//     alpha2: "sk",
//     alpha3: "svk",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "slovenia",
//     alpha2: "si",
//     alpha3: "svn",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "solomon islands",
//     alpha2: "sb",
//     alpha3: "slb",
//     currencyNumeriсCode: "090",
//   },
//   {
//     country: "somalia",
//     alpha2: "so",
//     alpha3: "som",
//     currencyNumeriсCode: "706",
//   },
//   {
//     country: "south africa",
//     alpha2: "za",
//     alpha3: "zaf",
//     currencyNumeriсCode: "710",
//   },
//   {
//     country: "south georgia and the south sandwich islands",
//     alpha2: "gs",
//     alpha3: "sgs",
//     currencyNumeriсCode: "239",
//   },
//   {
//     country: "south sudan",
//     alpha2: "ss",
//     alpha3: "ssd",
//     currencyNumeriсCode: "728",
//   },
//   {
//     country: "spain",
//     alpha2: "es",
//     alpha3: "esp",
//     currencyNumeriсCode: "978",
//   },
//   {
//     country: "sri lanka",
//     alpha2: "lk",
//     alpha3: "lka",
//     currencyNumeriсCode: "144",
//   },
//   {
//     country: "sudan (the)",
//     alpha2: "sd",
//     alpha3: "sdn",
//     currencyNumeriсCode: "729",
//   },
//   {
//     country: "suriname",
//     alpha2: "sr",
//     alpha3: "sur",
//     currencyNumeriсCode: "740",
//   },
//   {
//     country: "svalbard and jan mayen",
//     alpha2: "sj",
//     alpha3: "sjm",
//     currencyNumeriсCode: "744",
//   },
//   {
//     country: "sweden",
//     alpha2: "se",
//     alpha3: "swe",
//     currencyNumeriсCode: "752",
//   },
//   {
//     country: "switzerland",
//     alpha2: "ch",
//     alpha3: "che",
//     currencyNumeriсCode: "756",
//   },
//   {
//     country: "syrian arab republic",
//     alpha2: "sy",
//     alpha3: "syr",
//     currencyNumeriсCode: "760",
//   },
//   {
//     country: "taiwan (province of china)",
//     alpha2: "tw",
//     alpha3: "twn",
//     currencyNumeriсCode: "158",
//   },
//   {
//     country: "tajikistan",
//     alpha2: "tj",
//     alpha3: "tjk",
//     currencyNumeriсCode: "762",
//   },
//   {
//     country: "tanzania, united republic of",
//     alpha2: "tz",
//     alpha3: "tza",
//     currencyNumeriсCode: "834",
//   },
//   {
//     country: "thailand",
//     alpha2: "th",
//     alpha3: "tha",
//     currencyNumeriсCode: "764",
//   },
//   {
//     country: "timor-leste",
//     alpha2: "tl",
//     alpha3: "tls",
//     currencyNumeriсCode: "626",
//   },
//   {
//     country: "togo",
//     alpha2: "tg",
//     alpha3: "tgo",
//     currencyNumeriсCode: "768",
//   },
//   {
//     country: "tokelau",
//     alpha2: "tk",
//     alpha3: "tkl",
//     currencyNumeriсCode: "772",
//   },
//   {
//     country: "tonga",
//     alpha2: "to",
//     alpha3: "ton",
//     currencyNumeriсCode: "776",
//   },
//   {
//     country: "trinidad and tobago",
//     alpha2: "tt",
//     alpha3: "tto",
//     currencyNumeriсCode: "780",
//   },
//   {
//     country: "tunisia",
//     alpha2: "tn",
//     alpha3: "tun",
//     currencyNumeriсCode: "788",
//   },
//   {
//     country: "turkey",
//     alpha2: "tr",
//     alpha3: "tur",
//     currencyNumeriсCode: "949",
//   },
//   {
//     country: "turkmenistan",
//     alpha2: "tm",
//     alpha3: "tkm",
//     currencyNumeriсCode: "934",
//   },
//   {
//     country: "turks and caicos islands (the)",
//     alpha2: "tc",
//     alpha3: "tca",
//     currencyNumeriсCode: "796",
//   },
//   {
//     country: "tuvalu",
//     alpha2: "tv",
//     alpha3: "tuv",
//     currencyNumeriсCode: "798",
//   },
//   {
//     country: "uganda",
//     alpha2: "ug",
//     alpha3: "uga",
//     currencyNumeriсCode: "800",
//   },
//   {
//     country: "ukraine",
//     alpha2: "ua",
//     alpha3: "ukr",
//     currencyNumeriсCode: "980",
//   },
//   {
//     country: "united arab emirates (the)",
//     alpha2: "ae",
//     alpha3: "are",
//     currencyNumeriсCode: "784",
//   },
//   {
//     country: "united kingdom of great britain and northern ireland (the)",
//     alpha2: "gb",
//     alpha3: "gbr",
//     currencyNumeriсCode: "826",
//   },
//   {
//     country: "united states minor outlying islands (the)",
//     alpha2: "um",
//     alpha3: "umi",
//     currencyNumeriсCode: "581",
//   },
//   {
//     country: "united states of america (the)",
//     alpha2: "us",
//     alpha3: "usa",
//     currencyNumeriсCode: "840",
//   },
//   {
//     country: "uruguay",
//     alpha2: "uy",
//     alpha3: "ury",
//     currencyNumeriсCode: "858",
//   },
//   {
//     country: "uzbekistan",
//     alpha2: "uz",
//     alpha3: "uzb",
//     currencyNumeriсCode: "860",
//   },
//   {
//     country: "vanuatu",
//     alpha2: "vu",
//     alpha3: "vut",
//     currencyNumeriсCode: "548",
//   },
//   {
//     country: "venezuela (bolivarian republic of)",
//     alpha2: "ve",
//     alpha3: "ven",
//     currencyNumeriсCode: "862",
//   },
//   {
//     country: "viet nam",
//     alpha2: "vn",
//     alpha3: "vnm",
//     currencyNumeriсCode: "704",
//   },
//   {
//     country: "virgin islands (british)",
//     alpha2: "vg",
//     alpha3: "vgb",
//     currencyNumeriсCode: "092",
//   },
//   {
//     country: "virgin islands (u.s.)",
//     alpha2: "vi",
//     alpha3: "vir",
//     currencyNumeriсCode: "850",
//   },
//   {
//     country: "wallis and futuna",
//     alpha2: "wf",
//     alpha3: "wlf",
//     currencyNumeriсCode: "876",
//   },
//   {
//     country: "western sahara",
//     alpha2: "eh",
//     alpha3: "esh",
//     currencyNumeriсCode: "732",
//   },
//   {
//     country: "yemen",
//     alpha2: "ye",
//     alpha3: "yem",
//     currencyNumeriсCode: "886",
//   },
//   {
//     country: "zambia",
//     alpha2: "zm",
//     alpha3: "zmb",
//     currencyNumeriсCode: "894",
//   },
//   {
//     country: "zimbabwe",
//     alpha2: "zw",
//     alpha3: "zwe",
//     currencyNumeriсCode: "716",
//   },
//   {
//     country: "åland islands",
//     alpha2: "ax",
//     alpha3: "ala",
//     currencyNumeriсCode: "978",
//   },
// ];

// country and currqncy localization
const listCurrencyIsoData = [
  {
    country: "afghanistan", // country name
    alpha2: "af", // ALPHA-2 currency code
    alpha3: "afg", // ALPHA-3 currency code
    currencyNumericCode: "971", // digital code iso 4217 https://www.iban.com/currency-codes
    currencySymbol: "AFN", // letter code iso 4217 https://www.iban.com/currency-codes
  },
  {
    country: "albania",
    alpha2: "al",
    alpha3: "alb",
    currencyNumericCode: "008",
    currencySymbol: "ALL",
  },
  {
    country: "algeria",
    alpha2: "dz",
    alpha3: "dza",
    currencyNumericCode: "012",
    currencySymbol: "DZD",
  },
  {
    country: "american samoa",
    alpha2: "as",
    alpha3: "asm",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "andorra",
    alpha2: "ad",
    alpha3: "and",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "angola",
    alpha2: "ao",
    alpha3: "ago",
    currencyNumericCode: "973",
    currencySymbol: "AOA",
  },
  {
    country: "anguilla",
    alpha2: "ai",
    alpha3: "aia",
    currencyNumericCode: "951",
    currencySymbol: "XCD",
  },
  {
    country: "antarctica",
    alpha2: "aq",
    alpha3: "ata",
    currencyNumericCode: "010",
    currencySymbol: "",
  },
  {
    country: "antigua and barbuda",
    alpha2: "ag",
    alpha3: "atg",
    currencyNumericCode: "028",
    currencySymbol: "XCD",
  },
  {
    country: "argentina",
    alpha2: "ar",
    alpha3: "arg",
    currencyNumericCode: "032",
    currencySymbol: "ARS",
  },
  {
    country: "armenia",
    alpha2: "am",
    alpha3: "arm",
    currencyNumericCode: "051",
    currencySymbol: "AMD",
  },
  {
    country: "aruba",
    alpha2: "aw",
    alpha3: "abw",
    currencyNumericCode: "533",
    currencySymbol: "AWG",
  },
  {
    country: "australia",
    alpha2: "au",
    alpha3: "aus",
    currencyNumericCode: "036",
    currencySymbol: "AUD",
  },
  {
    country: "austria",
    alpha2: "at",
    alpha3: "aut",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "azerbaijan",
    alpha2: "az",
    alpha3: "aze",
    currencyNumericCode: "944",
    currencySymbol: "AZN",
  },
  {
    country: "bahamas (the)",
    alpha2: "bs",
    alpha3: "bhs",
    currencyNumericCode: "044",
    currencySymbol: "BSD",
  },
  {
    country: "bahrain",
    alpha2: "bh",
    alpha3: "bhr",
    currencyNumericCode: "048",
    currencySymbol: "BHD",
  },
  {
    country: "bangladesh",
    alpha2: "bd",
    alpha3: "bgd",
    currencyNumericCode: "050",
    currencySymbol: "BDT",
  },
  {
    country: "barbados",
    alpha2: "bb",
    alpha3: "brb",
    currencyNumericCode: "052",
    currencySymbol: "BBD",
  },
  {
    country: "belarus",
    alpha2: "by",
    alpha3: "blr",
    currencyNumericCode: "933",
    currencySymbol: "BYN",
  },
  {
    country: "belgium",
    alpha2: "be",
    alpha3: "bel",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "belize",
    alpha2: "bz",
    alpha3: "blz",
    currencyNumericCode: "084",
    currencySymbol: "BZD",
  },
  {
    country: "benin",
    alpha2: "bj",
    alpha3: "ben",
    currencyNumericCode: "952",
    currencySymbol: "XOF",
  },
  {
    country: "bermuda",
    alpha2: "bm",
    alpha3: "bmu",
    currencyNumericCode: "060",
    currencySymbol: "BMD",
  },
  {
    country: "bhutan",
    alpha2: "bt",
    alpha3: "btn",
    currencyNumericCode: "356",
    currencySymbol: "INR",
  },
  {
    country: "bolivia (plurinational state of)",
    alpha2: "bo",
    alpha3: "bol",
    currencyNumericCode: "068",
    currencySymbol: "BOB",
  },
  {
    country: "bonaire, sint eustatius and saba",
    alpha2: "bq",
    alpha3: "bes",
    currencyNumericCode: "535",
    currencySymbol: "USD",
  },
  {
    country: "bosnia and herzegovina",
    alpha2: "ba",
    alpha3: "bih",
    currencyNumericCode: "977",
    currencySymbol: "BAM",
  },
  {
    country: "botswana",
    alpha2: "bw",
    alpha3: "bwa",
    currencyNumericCode: "072",
    currencySymbol: "BWP",
  },
  {
    country: "bouvet island",
    alpha2: "bv",
    alpha3: "bvt",
    currencyNumericCode: "074",
    currencySymbol: "NOK",
  },
  {
    country: "brazil",
    alpha2: "br",
    alpha3: "bra",
    currencyNumericCode: "076",
    currencySymbol: "BRL",
  },
  {
    country: "british indian ocean territory (the)",
    alpha2: "io",
    alpha3: "iot",
    currencyNumericCode: "086",
    currencySymbol: "USD",
  },
  {
    country: "brunei darussalam",
    alpha2: "bn",
    alpha3: "brn",
    currencyNumericCode: "096",
    currencySymbol: "BND",
  },
  {
    country: "bulgaria",
    alpha2: "bg",
    alpha3: "bgr",
    currencyNumericCode: "975",
    currencySymbol: "BGN",
  },
  {
    country: "burkina faso",
    alpha2: "bf",
    alpha3: "bfa",
    currencyNumericCode: "854",
    currencySymbol: "XOF",
  },
  {
    country: "burundi",
    alpha2: "bi",
    alpha3: "bdi",
    currencyNumericCode: "108",
    currencySymbol: "BIF",
  },
  {
    country: "cabo verde",
    alpha2: "cv",
    alpha3: "cpv",
    currencyNumericCode: "132",
    currencySymbol: "CVE",
  },
  {
    country: "cambodia",
    alpha2: "kh",
    alpha3: "khm",
    currencyNumericCode: "116",
    currencySymbol: "KHR",
  },
  {
    country: "cameroon",
    alpha2: "cm",
    alpha3: "cmr",
    currencyNumericCode: "950",
    currencySymbol: "XAF",
  },
  {
    country: "canada",
    alpha2: "ca",
    alpha3: "can",
    currencyNumericCode: "124",
    currencySymbol: "CAD",
  },
  {
    country: "cayman islands (the)",
    alpha2: "ky",
    alpha3: "cym",
    currencyNumericCode: "136",
    currencySymbol: "KYD",
  },
  {
    country: "central african republic (the)",
    alpha2: "cf",
    alpha3: "caf",
    currencyNumericCode: "950",
    currencySymbol: "XAF",
  },
  {
    country: "chad",
    alpha2: "td",
    alpha3: "tcd",
    currencyNumericCode: "950",
    currencySymbol: "XAF",
  },
  {
    country: "chile",
    alpha2: "cl",
    alpha3: "chl",
    currencyNumericCode: "152",
    currencySymbol: "CLP",
  },
  {
    country: "china",
    alpha2: "cn",
    alpha3: "chn",
    currencyNumericCode: "156",
    currencySymbol: "CNY",
  },
  {
    country: "christmas island",
    alpha2: "cx",
    alpha3: "cxr",
    currencyNumericCode: "162",
    currencySymbol: "AUD",
  },
  {
    country: "cocos (keeling) islands (the)",
    alpha2: "cc",
    alpha3: "cck",
    currencyNumericCode: "166",
    currencySymbol: "AUD",
  },
  {
    country: "colombia",
    alpha2: "co",
    alpha3: "col",
    currencyNumericCode: "170",
    currencySymbol: "COP",
  },
  {
    country: "comoros (the)",
    alpha2: "km",
    alpha3: "com",
    currencyNumericCode: "174",
    currencySymbol: "KMF",
  },
  {
    country: "congo (the democratic republic of the)",
    alpha2: "cd",
    alpha3: "cod",
    currencyNumericCode: "976",
    currencySymbol: "CDF",
  },
  {
    country: "congo (the)",
    alpha2: "cg",
    alpha3: "cog",
    currencyNumericCode: "950",
    currencySymbol: "XAF",
  },
  {
    country: "cook islands (the)",
    alpha2: "ck",
    alpha3: "cok",
    currencyNumericCode: "184",
    currencySymbol: "NZD",
  },
  {
    country: "costa rica",
    alpha2: "cr",
    alpha3: "cri",
    currencyNumericCode: "188",
    currencySymbol: "CRC",
  },
  {
    country: "croatia",
    alpha2: "hr",
    alpha3: "hrv",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "cuba",
    alpha2: "cu",
    alpha3: "cub",
    currencyNumericCode: "192",
    currencySymbol: "CUP",
  },
  {
    country: "curaçao",
    alpha2: "cw",
    alpha3: "cuw",
    currencyNumericCode: "532",
    currencySymbol: "ANG",
  },
  {
    country: "cyprus",
    alpha2: "cy",
    alpha3: "cyp",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "czechia",
    alpha2: "cz",
    alpha3: "cze",
    currencyNumericCode: "203",
    currencySymbol: "CZK",
  },
  {
    country: "côte d'ivoire",
    alpha2: "ci",
    alpha3: "civ",
    currencyNumericCode: "952",
    currencySymbol: "XOF",
  },
  {
    country: "denmark",
    alpha2: "dk",
    alpha3: "dnk",
    currencyNumericCode: "208",
    currencySymbol: "DKK",
  },
  {
    country: "djibouti",
    alpha2: "dj",
    alpha3: "dji",
    currencyNumericCode: "262",
    currencySymbol: "DJF",
  },
  {
    country: "dominica",
    alpha2: "dm",
    alpha3: "dma",
    currencyNumericCode: "951",
    currencySymbol: "XCD",
  },
  {
    country: "dominican republic (the)",
    alpha2: "do",
    alpha3: "dom",
    currencyNumericCode: "214",
    currencySymbol: "DOP",
  },
  {
    country: "ecuador",
    alpha2: "ec",
    alpha3: "ecu",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "egypt",
    alpha2: "eg",
    alpha3: "egy",
    currencyNumericCode: "818",
    currencySymbol: "EGP",
  },
  {
    country: "el salvador",
    alpha2: "sv",
    alpha3: "slv",
    currencyNumericCode: "222",
    currencySymbol: "USD",
  },
  {
    country: "equatorial guinea",
    alpha2: "gq",
    alpha3: "gnq",
    currencyNumericCode: "950",
    currencySymbol: "XAF",
  },
  {
    country: "eritrea",
    alpha2: "er",
    alpha3: "eri",
    currencyNumericCode: "232",
    currencySymbol: "ERN",
  },
  {
    country: "estonia",
    alpha2: "ee",
    alpha3: "est",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "eswatini",
    alpha2: "sz",
    alpha3: "swz",
    currencyNumericCode: "748",
    currencySymbol: "SZL",
  },
  {
    country: "ethiopia",
    alpha2: "et",
    alpha3: "eth",
    currencyNumericCode: "230",
    currencySymbol: "ETB",
  },
  {
    country: "falkland islands (the) [malvinas]",
    alpha2: "fk",
    alpha3: "flk",
    currencyNumericCode: "238",
    currencySymbol: "FKP",
  },
  {
    country: "faroe islands (the)",
    alpha2: "fo",
    alpha3: "fro",
    currencyNumericCode: "208",
    currencySymbol: "DKK",
  },
  {
    country: "fiji",
    alpha2: "fj",
    alpha3: "fji",
    currencyNumericCode: "242",
    currencySymbol: "FJD",
  },
  {
    country: "finland",
    alpha2: "fi",
    alpha3: "fin",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "france",
    alpha2: "fr",
    alpha3: "fra",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "french guiana",
    alpha2: "gf",
    alpha3: "guf",
    currencyNumericCode: "254",
    currencySymbol: "EUR",
  },
  {
    country: "french polynesia",
    alpha2: "pf",
    alpha3: "pyf",
    currencyNumericCode: "953",
    currencySymbol: "XPF",
  },
  {
    country: "french southern territories (the)",
    alpha2: "tf",
    alpha3: "atf",
    currencyNumericCode: "260",
    currencySymbol: "EUR", // checked
  },
  {
    country: "gabon",
    alpha2: "ga",
    alpha3: "gab",
    currencyNumericCode: "950",
    currencySymbol: "XAF",
  },
  {
    country: "gambia (the)",
    alpha2: "gm",
    alpha3: "gmb",
    currencyNumericCode: "270",
    currencySymbol: "GMD",
  },
  {
    country: "georgia",
    alpha2: "ge",
    alpha3: "geo",
    currencyNumericCode: "981",
    currencySymbol: "GEL",
  },
  {
    country: "germany",
    alpha2: "de",
    alpha3: "deu",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "ghana",
    alpha2: "gh",
    alpha3: "gha",
    currencyNumericCode: "936",
    currencySymbol: "GHS",
  },
  {
    country: "gibraltar",
    alpha2: "gi",
    alpha3: "gib",
    currencyNumericCode: "292",
    currencySymbol: "GIP",
  },
  {
    country: "greece",
    alpha2: "gr",
    alpha3: "grc",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "greenland",
    alpha2: "gl",
    alpha3: "grl",
    currencyNumericCode: "208",
    currencySymbol: "DKK",
  },
  {
    country: "grenada",
    alpha2: "gd",
    alpha3: "grd",
    currencyNumericCode: "951",
    currencySymbol: "XCD",
  },
  {
    country: "guadeloupe",
    alpha2: "gp",
    alpha3: "glp",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "guam",
    alpha2: "gu",
    alpha3: "gum",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "guatemala",
    alpha2: "gt",
    alpha3: "gtm",
    currencyNumericCode: "826",
    currencySymbol: "GTQ",
  },
  {
    country: "guernsey",
    alpha2: "gg",
    alpha3: "ggy",
    currencyNumericCode: "826",
    currencySymbol: "GBP",
  },
  {
    country: "guinea",
    alpha2: "gn",
    alpha3: "gin",
    currencyNumericCode: "324",
    currencySymbol: "GNF",
  },
  {
    country: "guinea-bissau",
    alpha2: "gw",
    alpha3: "gnb",
    currencyNumericCode: "952",
    currencySymbol: "XOF",
  },
  {
    country: "guyana",
    alpha2: "gy",
    alpha3: "guy",
    currencyNumericCode: "328",
    currencySymbol: "GYD",
  },
  {
    country: "haiti",
    alpha2: "ht",
    alpha3: "hti",
    currencyNumericCode: "332",
    currencySymbol: "HTG",
  },
  {
    country: "heard island and mcdonald islands",
    alpha2: "hm",
    alpha3: "hmd",
    currencyNumericCode: "036",
    currencySymbol: "AUD",
  },
  {
    country: "holy see (the)",
    alpha2: "va",
    alpha3: "vat",
    currencyNumericCode: "336",
    currencySymbol: "EUR",
  },
  {
    country: "honduras",
    alpha2: "hn",
    alpha3: "hnd",
    currencyNumericCode: "340",
    currencySymbol: "HNL",
  },
  {
    country: "hong kong",
    alpha2: "hk",
    alpha3: "hkg",
    currencyNumericCode: "344",
    currencySymbol: "HKD",
  },
  {
    country: "hungary",
    alpha2: "hu",
    alpha3: "hun",
    currencyNumericCode: "348",
    currencySymbol: "HUF",
  },
  {
    country: "iceland",
    alpha2: "is",
    alpha3: "isl",
    currencyNumericCode: "352",
    currencySymbol: "ISK",
  },
  {
    country: "india",
    alpha2: "in",
    alpha3: "ind",
    currencyNumericCode: "356",
    currencySymbol: "INR",
  },
  {
    country: "indonesia",
    alpha2: "id",
    alpha3: "idn",
    currencyNumericCode: "360",
    currencySymbol: "IDR",
  },
  {
    country: "iran (islamic republic of)",
    alpha2: "ir",
    alpha3: "irn",
    currencyNumericCode: "364",
    currencySymbol: "IRR",
  },
  {
    country: "iraq",
    alpha2: "iq",
    alpha3: "irq",
    currencyNumericCode: "368",
    currencySymbol: "IQD",
  },
  {
    country: "ireland",
    alpha2: "ie",
    alpha3: "irl",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "isle of man",
    alpha2: "im",
    alpha3: "imn",
    currencyNumericCode: "826",
    currencySymbol: "GBP",
  },
  {
    country: "israel",
    alpha2: "il",
    alpha3: "isr",
    currencyNumericCode: "376",
    currencySymbol: "ILS",
  },
  {
    country: "italy",
    alpha2: "it",
    alpha3: "ita",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "jamaica",
    alpha2: "jm",
    alpha3: "jam",
    currencyNumericCode: "388",
    currencySymbol: "JMD",
  },
  {
    country: "japan",
    alpha2: "jp",
    alpha3: "jpn",
    currencyNumericCode: "392",
    currencySymbol: "JPY",
  },
  {
    country: "jersey",
    alpha2: "je",
    alpha3: "jey",
    currencyNumericCode: "826",
    currencySymbol: "GBP",
  },
  {
    country: "jordan",
    alpha2: "jo",
    alpha3: "jor",
    currencyNumericCode: "400",
    currencySymbol: "JOD",
  },
  {
    country: "kazakhstan",
    alpha2: "kz",
    alpha3: "kaz",
    currencyNumericCode: "398",
    currencySymbol: "KZT",
  },
  {
    country: "kenya",
    alpha2: "ke",
    alpha3: "ken",
    currencyNumericCode: "404",
    currencySymbol: "KES",
  },
  {
    country: "kiribati",
    alpha2: "ki",
    alpha3: "kir",
    currencyNumericCode: "036",
    currencySymbol: "AUD",
  },
  {
    country: "korea (the democratic people's republic of)", // -
    alpha2: "kp",
    alpha3: "prk",
    currencyNumericCode: "408",
    currencySymbol: "KPW",
  },
  {
    country: "korea (the republic of)", // -
    alpha2: "kr",
    alpha3: "kor",
    currencyNumericCode: "410",
    currencySymbol: "KRW",
  },
  {
    country: "kuwait",
    alpha2: "kw",
    alpha3: "kwt",
    currencyNumericCode: "414",
    currencySymbol: "KWD",
  },
  {
    country: "kyrgyzstan",
    alpha2: "kg",
    alpha3: "kgz",
    currencyNumericCode: "417",
    currencySymbol: "KGS",
  },
  {
    country: "lao people's democratic republic (the)",
    alpha2: "la",
    alpha3: "lao",
    currencyNumericCode: "418",
    currencySymbol: "LAK",
  },
  {
    country: "latvia",
    alpha2: "lv",
    alpha3: "lva",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "lebanon",
    alpha2: "lb",
    alpha3: "lbn",
    currencyNumericCode: "422",
    currencySymbol: "LBP",
  },
  {
    country: "lesotho",
    alpha2: "ls",
    alpha3: "lso",
    currencyNumericCode: "426",
    currencySymbol: "LSL",
  },
  {
    country: "liberia",
    alpha2: "lr",
    alpha3: "lbr",
    currencyNumericCode: "430",
    currencySymbol: "LRD",
  },
  {
    country: "libya",
    alpha2: "ly",
    alpha3: "lby",
    currencyNumericCode: "434",
    currencySymbol: "LYD",
  },
  {
    country: "liechtenstein",
    alpha2: "li",
    alpha3: "lie",
    currencyNumericCode: "756",
    currencySymbol: "CHF",
  },
  {
    country: "lithuania",
    alpha2: "lt",
    alpha3: "ltu",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "luxembourg",
    alpha2: "lu",
    alpha3: "lux",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "macao",
    alpha2: "mo",
    alpha3: "mac",
    currencyNumericCode: "446",
    currencySymbol: "MOP",
  },
  {
    country: "madagascar",
    alpha2: "mg",
    alpha3: "mdg",
    currencyNumericCode: "454",
    currencySymbol: "MGA",
  },
  {
    country: "malawi",
    alpha2: "mw",
    alpha3: "mwi",
    currencyNumericCode: "454",
    currencySymbol: "MWK",
  },
  {
    country: "malaysia",
    alpha2: "my",
    alpha3: "mys",
    currencyNumericCode: "458",
    currencySymbol: "MYR",
  },
  {
    country: "maldives",
    alpha2: "mv",
    alpha3: "mdv",
    currencyNumericCode: "462",
    currencySymbol: "MVR",
  },
  {
    country: "mali",
    alpha2: "ml",
    alpha3: "mli",
    currencyNumericCode: "952",
    currencySymbol: "XOF",
  },
  {
    country: "malta",
    alpha2: "mt",
    alpha3: "mlt",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "marshall islands (the)",
    alpha2: "mh",
    alpha3: "mhl",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "martinique",
    alpha2: "mq",
    alpha3: "mtq",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "mauritania",
    alpha2: "mr",
    alpha3: "mrt",
    currencyNumericCode: "929",
    currencySymbol: "MRU",
  },
  {
    country: "mauritius",
    alpha2: "mu",
    alpha3: "mus",
    currencyNumericCode: "480",
    currencySymbol: "MUR",
  },
  {
    country: "mayotte",
    alpha2: "yt",
    alpha3: "myt",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "mexico",
    alpha2: "mx",
    alpha3: "mex",
    currencyNumericCode: "484",
    currencySymbol: "MXN",
  },
  {
    country: "micronesia (federated states of)",
    alpha2: "fm",
    alpha3: "fsm",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "moldova (the republic of)",
    alpha2: "md",
    alpha3: "mda",
    currencyNumericCode: "498",
    currencySymbol: "MDL",
  },
  {
    country: "monaco",
    alpha2: "mc",
    alpha3: "mco",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "mongolia",
    alpha2: "mn",
    alpha3: "mng",
    currencyNumericCode: "496",
    currencySymbol: "MNT",
  },
  {
    country: "montenegro",
    alpha2: "me",
    alpha3: "mne",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "montserrat",
    alpha2: "ms",
    alpha3: "msr",
    currencyNumericCode: "951",
    currencySymbol: "XCD",
  },
  {
    country: "morocco",
    alpha2: "ma",
    alpha3: "mar",
    currencyNumericCode: "504",
    currencySymbol: "MAD",
  },
  {
    country: "mozambique",
    alpha2: "mz",
    alpha3: "moz",
    currencyNumericCode: "943",
    currencySymbol: "MZN",
  },
  {
    country: "myanmar",
    alpha2: "mm",
    alpha3: "mmr",
    currencyNumericCode: "104",
    currencySymbol: "MMK",
  },
  {
    country: "namibia",
    alpha2: "na",
    alpha3: "nam",
    currencyNumericCode: "516",
    currencySymbol: "NAD",
  },
  {
    country: "nauru",
    alpha2: "nr",
    alpha3: "nru",
    currencyNumericCode: "682",
    currencySymbol: "AUD",
  },
  {
    country: "nepal",
    alpha2: "np",
    alpha3: "npl",
    currencyNumericCode: "524",
    currencySymbol: "NPR",
  },
  {
    country: "netherlands",
    alpha2: "nl",
    alpha3: "nld",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "new caledonia",
    alpha2: "nc",
    alpha3: "ncl",
    currencyNumericCode: "953",
    currencySymbol: "XPF",
  },
  {
    country: "new zealand",
    alpha2: "nz",
    alpha3: "nzl",
    currencyNumericCode: "554",
    currencySymbol: "NZD",
  },
  {
    country: "nicaragua",
    alpha2: "ni",
    alpha3: "nic",
    currencyNumericCode: "558",
    currencySymbol: "NIO",
  },
  {
    country: "niger (the)",
    alpha2: "ne",
    alpha3: "ner",
    currencyNumericCode: "952",
    currencySymbol: "XOF",
  },
  {
    country: "nigeria",
    alpha2: "ng",
    alpha3: "nga",
    currencyNumericCode: "566",
    currencySymbol: "NGN",
  },
  {
    country: "niue",
    alpha2: "nu",
    alpha3: "niu",
    currencyNumericCode: "554",
    currencySymbol: "NZD",
  },
  {
    country: "norfolk island",
    alpha2: "nf",
    alpha3: "nfk",
    currencyNumericCode: "036",
    currencySymbol: "AUD",
  },
  {
    country: "northern mariana islands (the)",
    alpha2: "mp",
    alpha3: "mnp",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "norway", // checked
    alpha2: "no",
    alpha3: "nor",
    currencyNumericCode: "578",
    currencySymbol: "NOK",
  },
  {
    country: "oman",
    alpha2: "om",
    alpha3: "omn",
    currencyNumericCode: "512",
    currencySymbol: "OMR",
  },
  {
    country: "pakistan",
    alpha2: "pk",
    alpha3: "pak",
    currencyNumericCode: "586",
    currencySymbol: "PKR",
  },
  {
    country: "palau",
    alpha2: "pw",
    alpha3: "plw",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "palestine, state of",
    alpha2: "ps",
    alpha3: "pse",
    currencyNumericCode: "376",
    currencySymbol: "ILS",
  },
  {
    country: "panama",
    alpha2: "pa",
    alpha3: "pan",
    currencyNumericCode: "590",
    currencySymbol: "PAB",
  },
  {
    country: "papua new guinea",
    alpha2: "pg",
    alpha3: "png",
    currencyNumericCode: "598",
    currencySymbol: "PGK",
  },
  {
    country: "paraguay",
    alpha2: "py",
    alpha3: "pry",
    currencyNumericCode: "600",
    currencySymbol: "PYG",
  },
  {
    country: "peru",
    alpha2: "pe",
    alpha3: "per",
    currencyNumericCode: "604",
    currencySymbol: "PEN",
  },
  {
    country: "philippines (the)",
    alpha2: "ph",
    alpha3: "phl",
    currencyNumericCode: "608",
    currencySymbol: "PHP",
  },
  {
    country: "pitcairn",
    alpha2: "pn",
    alpha3: "pcn",
    currencyNumericCode: "554",
    currencySymbol: "NZD",
  },
  {
    country: "poland",
    alpha2: "pl",
    alpha3: "pol",
    currencyNumericCode: "985",
    currencySymbol: "PLN",
  },
  {
    country: "portugal",
    alpha2: "pt",
    alpha3: "prt",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "puerto rico",
    alpha2: "pr",
    alpha3: "pri",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "qatar",
    alpha2: "qa",
    alpha3: "qat",
    currencyNumericCode: "634",
    currencySymbol: "QAR",
  },
  {
    country: "republic of north macedonia",
    alpha2: "mk",
    alpha3: "mkd",
    currencyNumericCode: "807",
    currencySymbol: "MKD",
  },
  {
    country: "romania",
    alpha2: "ro",
    alpha3: "rou",
    currencyNumericCode: "946",
    currencySymbol: "RON",
  },
  {
    country: "russian federation (the)",
    alpha2: "ru",
    alpha3: "rus",
    currencyNumericCode: "643",
    currencySymbol: "RUB",
  },
  {
    country: "rwanda",
    alpha2: "rw",
    alpha3: "rwa",
    currencyNumericCode: "646",
    currencySymbol: "RWF",
  },
  {
    country: "réunion",
    alpha2: "re",
    alpha3: "reu",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "saint barthélemy",
    alpha2: "bl",
    alpha3: "blm",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "saint helena, ascension and tristan da cunha",
    alpha2: "sh",
    alpha3: "shn",
    currencyNumericCode: "654",
    currencySymbol: "SHP",
  },
  {
    country: "saint kitts and nevis",
    alpha2: "kn",
    alpha3: "kna",
    currencyNumericCode: "659",
    currencySymbol: "XCD",
  },
  {
    country: "saint lucia",
    alpha2: "lc",
    alpha3: "lca",
    currencyNumericCode: "662",
    currencySymbol: "XCD",
  },
  {
    country: "saint martin (french part)",
    alpha2: "mf",
    alpha3: "maf",
    currencyNumericCode: "663",
    currencySymbol: "EUR",
  },
  {
    country: "saint pierre and miquelon",
    alpha2: "pm",
    alpha3: "spm",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "saint vincent and the grenadines",
    alpha2: "vc",
    alpha3: "vct",
    currencyNumericCode: "670",
    currencySymbol: "XCD",
  },
  {
    country: "samoa",
    alpha2: "ws",
    alpha3: "wsm",
    currencyNumericCode: "882",
    currencySymbol: "WST",
  },
  {
    country: "san marino",
    alpha2: "sm",
    alpha3: "smr",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "sao tome and principe",
    alpha2: "st",
    alpha3: "stp",
    currencyNumericCode: "930",
    currencySymbol: "STN",
  },
  {
    country: "saudi arabia",
    alpha2: "sa",
    alpha3: "sau",
    currencyNumericCode: "682",
    currencySymbol: "SAR",
  },
  {
    country: "senegal",
    alpha2: "sn",
    alpha3: "sen",
    currencyNumericCode: "952",
    currencySymbol: "XOF",
  },
  {
    country: "serbia",
    alpha2: "rs",
    alpha3: "srb",
    currencyNumericCode: "941",
    currencySymbol: "RSD",
  },
  {
    country: "seychelles",
    alpha2: "sc",
    alpha3: "syc",
    currencyNumericCode: "690",
    currencySymbol: "SCR",
  },
  {
    country: "sierra leone",
    alpha2: "sl",
    alpha3: "sle",
    currencyNumericCode: "925",
    currencySymbol: "SLL",
  },
  {
    country: "singapore",
    alpha2: "sg",
    alpha3: "sgp",
    currencyNumericCode: "702",
    currencySymbol: "SGD",
  },
  {
    country: "sint maarten (dutch part)",
    alpha2: "sx",
    alpha3: "sxm",
    currencyNumericCode: "532",
    currencySymbol: "ANG",
  },
  {
    country: "slovakia",
    alpha2: "sk",
    alpha3: "svk",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "slovenia",
    alpha2: "si",
    alpha3: "svn",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "solomon islands",
    alpha2: "sb",
    alpha3: "slb",
    currencyNumericCode: "090",
    currencySymbol: "SBD",
  },
  {
    country: "somalia",
    alpha2: "so",
    alpha3: "som",
    currencyNumericCode: "706",
    currencySymbol: "SOS",
  },
  {
    country: "south africa",
    alpha2: "za",
    alpha3: "zaf",
    currencyNumericCode: "710",
    currencySymbol: "ZAR",
  },
  {
    country: "south georgia and the south sandwich islands",
    alpha2: "gs",
    alpha3: "sgs",
    currencyNumericCode: "826",
    currencySymbol: "GBP",
  },
  {
    country: "south sudan",
    alpha2: "ss",
    alpha3: "ssd",
    currencyNumericCode: "728",
    currencySymbol: "SSP",
  },
  {
    country: "spain",
    alpha2: "es",
    alpha3: "esp",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "sri lanka",
    alpha2: "lk",
    alpha3: "lka",
    currencyNumericCode: "144",
    currencySymbol: "LKR",
  },
  {
    country: "sudan (the)",
    alpha2: "sd",
    alpha3: "sdn",
    currencyNumericCode: "938",
    currencySymbol: "SDG",
  },
  {
    country: "suriname",
    alpha2: "sr",
    alpha3: "sur",
    currencyNumericCode: "968",
    currencySymbol: "SRD",
  },
  {
    country: "svalbard and jan mayen",
    alpha2: "sj",
    alpha3: "sjm",
    currencyNumericCode: "578",
    currencySymbol: "NOK",
  },
  {
    country: "sweden",
    alpha2: "se",
    alpha3: "swe",
    currencyNumericCode: "752",
    currencySymbol: "SEK",
  },
  {
    country: "switzerland",
    alpha2: "ch",
    alpha3: "che",
    currencyNumericCode: "756",
    currencySymbol: "CHF",
  },
  {
    country: "syrian arab republic",
    alpha2: "sy",
    alpha3: "syr",
    currencyNumericCode: "760",
    currencySymbol: "SYP",
  },
  {
    country: "taiwan (province of china)",
    alpha2: "tw",
    alpha3: "twn",
    currencyNumericCode: "901",
    currencySymbol: "TWD",
  },
  {
    country: "tajikistan",
    alpha2: "tj",
    alpha3: "tjk",
    currencyNumericCode: "972",
    currencySymbol: "TJS",
  },
  {
    country: "tanzania, united republic of",
    alpha2: "tz",
    alpha3: "tza",
    currencyNumericCode: "834",
    currencySymbol: "TZS",
  },
  {
    country: "thailand",
    alpha2: "th",
    alpha3: "tha",
    currencyNumericCode: "764",
    currencySymbol: "THB",
  },
  {
    country: "timor-leste",
    alpha2: "tl",
    alpha3: "tls",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "togo",
    alpha2: "tg",
    alpha3: "tgo",
    currencyNumericCode: "952",
    currencySymbol: "XOF",
  },
  {
    country: "tokelau",
    alpha2: "tk",
    alpha3: "tkl",
    currencyNumericCode: "554",
    currencySymbol: "NZD",
  },
  {
    country: "tonga",
    alpha2: "to",
    alpha3: "ton",
    currencyNumericCode: "776",
    currencySymbol: "TOP",
  },
  {
    country: "trinidad and tobago",
    alpha2: "tt",
    alpha3: "tto",
    currencyNumericCode: "780",
    currencySymbol: "TTD",
  },
  {
    country: "tunisia",
    alpha2: "tn",
    alpha3: "tun",
    currencyNumericCode: "788",
    currencySymbol: "TND",
  },
  {
    country: "turkey",
    alpha2: "tr",
    alpha3: "tur",
    currencyNumericCode: "949",
    currencySymbol: "TRY",
  },
  {
    country: "turkmenistan",
    alpha2: "tm",
    alpha3: "tkm",
    currencyNumericCode: "934",
    currencySymbol: "TMT",
  },
  {
    country: "turks and caicos islands (the)",
    alpha2: "tc",
    alpha3: "tca",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "tuvalu",
    alpha2: "tv",
    alpha3: "tuv",
    currencyNumericCode: "682",
    currencySymbol: "AUD",
  },
  {
    country: "uganda",
    alpha2: "ug",
    alpha3: "uga",
    currencyNumericCode: "800",
    currencySymbol: "UGX",
  },
  {
    country: "ukraine",
    alpha2: "ua",
    alpha3: "ukr",
    currencyNumericCode: "980",
    currencySymbol: "UAH",
  },
  {
    country: "united arab emirates (the)",
    alpha2: "ae",
    alpha3: "are",
    currencyNumericCode: "784",
    currencySymbol: "AED",
  },
  {
    country: "united kingdom of great britain and northern ireland (the)",
    alpha2: "gb",
    alpha3: "gbr",
    currencyNumericCode: "826",
    currencySymbol: "GBP",
  },
  {
    country: "united states minor outlying islands (the)",
    alpha2: "um",
    alpha3: "umi",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "united states of america (the)",
    alpha2: "us",
    alpha3: "usa",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "uruguay",
    alpha2: "uy",
    alpha3: "ury",
    currencyNumericCode: "858",
    currencySymbol: "UYU",
  },
  {
    country: "uzbekistan",
    alpha2: "uz",
    alpha3: "uzb",
    currencyNumericCode: "860",
    currencySymbol: "UZS",
  },
  {
    country: "vanuatu",
    alpha2: "vu",
    alpha3: "vut",
    currencyNumericCode: "548",
    currencySymbol: "VUV",
  },
  {
    country: "venezuela (bolivarian republic of)",
    alpha2: "ve",
    alpha3: "ven",
    currencyNumericCode: "928",
    currencySymbol: "VES",
  },
  {
    country: "viet nam",
    alpha2: "vn",
    alpha3: "vnm",
    currencyNumericCode: "704",
    currencySymbol: "VND",
  },
  {
    country: "virgin islands (british)",
    alpha2: "vg",
    alpha3: "vgb",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "virgin islands (u.s.)",
    alpha2: "vi",
    alpha3: "vir",
    currencyNumericCode: "840",
    currencySymbol: "USD",
  },
  {
    country: "wallis and futuna",
    alpha2: "wf",
    alpha3: "wlf",
    currencyNumericCode: "953",
    currencySymbol: "XPF",
  },
  {
    country: "western sahara",
    alpha2: "eh",
    alpha3: "esh",
    currencyNumericCode: "504",
    currencySymbol: "MAD",
  },
  {
    country: "yemen",
    alpha2: "ye",
    alpha3: "yem",
    currencyNumericCode: "886",
    currencySymbol: "YER",
  },
  {
    country: "zambia",
    alpha2: "zm",
    alpha3: "zmb",
    currencyNumericCode: "967",
    currencySymbol: "ZMW",
  },
  {
    country: "zimbabwe", // -
    alpha2: "zw",
    alpha3: "zwe",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
  {
    country: "åland islands",
    alpha2: "ax",
    alpha3: "ala",
    currencyNumericCode: "978",
    currencySymbol: "EUR",
  },
];
